### ISSUE TITLE
Allow \Drupal::setContainer when inspecting static calls to \Drupal

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#102]
Unit tests will mock the service container and often call `\Drupal::setContainer`. The `GlobalDrupalDependencyInjectionRule` rule should ignore calls to `\Drupal` when the method is `setContainer` or `unsetContainer`

**Comment by MPParsley** [comment]
Hi @mglaman, the Drupal docs often mention examples that are using static Drupal:: calls to get services but I wonder if it's a good practice to directly access the container as such?
