### ISSUE TITLE
Drupal documentations says plugin manager cache tags are option, but error is thrown if they are absent

### ISSUE THREAD

**Issue by alberto56** [mglaman/phpstan-drupal#112]
The [documentation](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Plugin%21DefaultPluginManager.php/function/DefaultPluginManager%3A%3AsetCacheBackend/8.2.x) for DefaultPluginManager::setCacheBackend() says:

> hen providing a list of cache tags, the cached plugin definitions are tagged with the provided cache tags. These cache tags can then be used to clear the corresponding cached plugin definitions. Note that this should be used with care! For clearing all cached plugin definitions of a plugin manager, call that plugin manager's clearCachedDefinitions() method. Only use cache tags when cached plugin definitions should be cleared along with other, related cache entries.

Which leads me to think the cache tags are optional; however when I run the static analysis against code which does not provide cache tags I get:

> Plugin manager has cache backend specified but does not declare cache tags.

Where could one get more info on the rationale behind this? Thanks!

**Comment by mglaman** [comment]
I guess I didn't read the documentation well enough. Makes sense to drop the rule.
