### ISSUE TITLE
Provide more info on the "Plugin definitions cannot be altered" error

### ISSUE THREAD

**Issue by alberto56** [mglaman/phpstan-drupal#113]
When following a number of tutorials online including the [examples](https://github.com/drupalprojects/examples/tree/8.x-1.x/plugin_type_example) module, and running the code through phpstan-drupal, we get the following error for Plugin definitions:

    Line 28 Plugin definitions cannot be altered

The code is:

    // line 28
    class MyPluginManager extends DefaultPluginManager {

Where could I get more info on this error and how to fix it?

**Comment by mglaman** [comment]
We should add a tip to explain the call to the alter info method

**Comment by gaelg** [comment]
I guess you mean something like this? https://api.druphelp.com/api/facets/src%21Widget%21WidgetPluginManager.php/8

**Comment by alberto56** [comment]
@gaelg although your link is an example of how a plugin should be declared, it is still not clear to me from that API documentation what a "definition" is, what "altering" it means, why I cannot alter it; and how my creating a subclass of DefaultPluginManager alters the definition; generally the error does not provide actionable information on what to do. Still, a link to that page might be useful.

Generally, what I would suggest is some sort of plain-language explanation as to why that error occurs.

[The code which generates the error is here](https://github.com/mglaman/phpstan-drupal/blob/46a78fe54c18e1528b67390eb34ab7998d70e485/src/Rules/Classes/PluginManagerInspectionRule.php#L54-L71).

Something like: 

> Line 28 Plugins should contain calls to alterInfo() if xyz because abc.

(I admit I still do not understand it myself.)

This might provide more guidance to developers who might otherwise be tempted to [ignore the error](https://github.com/mglaman/phpstan-drupal/blame/b47279a38be9a742185154e3f6edeea888e221d5/README.md#L76), which would lower overall code quality.

**Comment by gaelg** [comment]
@alberto56 yes, I fully agree. I just posted this link in case it can help to get rid of the error, until we get a good error message, as mglaman answer was somewhat vague. But it's still not clear to me what must be done and why. From what I figured out until now, it looks like the current rule checks that your subclass has a __construct() method calling $this->alterInfo() (calls in parent  __construct() method seems not to be enough).
It seems the aim is to ensure plugin defintions are alterable by other modules through drupal hooks.

NB: A same kind of problem happen if the constructor method doesn't have $this->setCacheBackend().

**Comment by Unifex** [comment]
Just came across this while evaluating custom code from old coworkers for PHP 8.1 readiness.

It's still a thing and, unfortunately, I don't understand how to resolve it.  Looking at the code @alberto56 linked to isn't making it any clearer either.  I think...

It appears to be looking for `alterInfo` but I'm not sure what that is.  The file I have that triggered this resides in `MY_MODULE/src/Manager/MyPluginManager.php`  The class there extends `DefaultPluginManager`. The line that throws the error is `class MyPluginManager extends DefaultPluginManager {` and looking at that there is an `alterInfo()` method.  This is in use by an enormous number of `MyThingManager` class files.

The initial commit that introduced this was [5 years ago](https://github.com/mglaman/phpstan-drupal/commit/422596b11fc48af3d89c241935d6655d958e5903), but unfortunately doesn't explain much about this particular check beyond the rather clear problem.

Given the error looks to be coming from the `DefaultPluginManager` class, is this actually a real error?

**Comment by joshsedl** [comment]
I agree with @Unifex this seems to be a false positive. We get the same error in the Fences Module:
https://git.drupalcode.org/project/fences/-/blob/3.x/src/TagManager.php?ref_type=heads#L18

` 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ---------------------------------------
  Line   TagManager.php
 ------ ---------------------------------------
  18     Plugin definitions cannot be altered.
 ------ ---------------------------------------
 `
 
 The "TagManager" class doesn't implement alterInfo(), but extends "DefaultPluginManager".

**Comment by bradjones1** [comment]
I get this as well when overriding `EntityTypeManager`.

**Comment by JPustkuchen** [comment]
@mglaman the error mentioned by @joshsedl can still be seen / reproduced in fences: https://git.drupalcode.org/project/fences/-/jobs/2275024

Perhaps that helps to understand and resolve it?
I created an issue for that at fences: https://www.drupal.org/project/fences/issues/3464650

**Comment by bkosborne** [comment]
I think this inspection is here to ensure that if you have a plugin manger, that you have a constructor that calls the alterInfo method, allowing definitions to be altered. The message is a bit confusing "Plugin definitions cannot be altered." I took this to mean that I was altering a plugin definition in my code and that it is not allowed to do that. But what it really means is that I have a plugin manager defined in such a way that prevents its plugins from being altered by other modules.

However, it's a false positive when _extending an existing plugin manager_. The inspection needs to detect if the class extends a plugin manager that already has a construct with the call to alterInfo.

**Comment by mglaman** [comment]
Getting around to this now that I am at DrupalCon Barcelona. I will improve the error message

**Comment by mglaman** [comment]
This isn't a false positive in https://git.drupalcode.org/project/fences/-/blob/3.x/src/TagManager.php?ref_type=heads#L18

```
  public function __construct(ModuleHandlerInterface $module_handler, ThemeHandlerInterface $theme_handler, CacheBackendInterface $cache_backend) {
    $this->moduleHandler = $module_handler;
    $this->themeHandler = $theme_handler;
    $this->setCacheBackend($cache_backend, 'fences', ['fences']);
  }
```

This does not call `alterInfo` to enable an alter hook.

> I get this as well when overriding EntityTypeManager.

This code is very old and very dumb, unfortunately.

**Comment by mglaman** [comment]
https://github.com/mglaman/phpstan-drupal/pull/799 aims to improve the error message, but it will break existing baseline/explicit ignores:

```
                [
                    'Plugin manager must call alterInfo to allow plugin definitions to be altered.',
                    9,
                    'For example, to invoke hook_mymodule_data_alter() call alterInfo with "mymodule_data".'
                ],
```

Example error and tip to explain.

**Comment by mglaman** [comment]
```
 ------ ----------------------------------------------------------------------- 
  Line   core/modules/migrate/src/Plugin/MigrateSourcePluginManager.php         
 ------ ----------------------------------------------------------------------- 
  21     Plugin managers must call alterInfo to allow plugin definitions to be  
         altered.                                                               
         💡 For example, to invoke hook_mymodule_data_alter() call alterInfo    
            with "mymodule_data".                                               
 ------ ----------------------------------------------------------------------- 
```

**Comment by mglaman** [comment]
Since `alterInfo` isn't required, I'm making this rule _opt in_ and not turned on by default.

**Comment by AdamPS** [comment]
Thanks
