### ISSUE TITLE
Ignore return type hints for Drupal hooks

### ISSUE THREAD

**Issue by markhalliwell** [mglaman/phpstan-drupal#130]
```neon
  # Ignore certain standards for legacy procedural functions in module, theme, profile and includes.
  # Specifically centered around hook/alters and lack of proper types.
  reportUnmatchedIgnoredErrors: false
  ignoreErrors:
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has no return typehint specified\./'
      path: *.module
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) return type has no value type specified/'
      path: *.module
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has parameter .* no value type specified/'
      path: *.module
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has no return typehint specified\./'
      path: *.theme
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) return type has no value type specified/'
      path: *.theme
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has parameter .* no value type specified/'
      path: *.theme
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has no return typehint specified\./'
      path: *.profile
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) return type has no value type specified/'
      path: *.profile
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has parameter .* no value type specified/'
      path: *.profile
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has no return typehint specified\./'
      path: *.inc
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) return type has no value type specified/'
      path: *.inc
    -
      message: '/^Function [a-zA-Z0-9\\_]+\(\) has parameter .* no value type specified/'
      path: *.inc
```

**Comment by mglaman** [comment]
I don't know if this extension should be enforcing this across the board. For instance, I care about these things in my custom code. Maybe it should just exclude contrib? Or maybe provide this as an option configuration folks can include to help silence.

**Comment by markcarver** [comment]
Well, generally speaking without this it's incompatible with phpcs, which requires the docblock for hooks/alter implementations to be a single line: `Implements hook_*().`.

**Comment by markcarver** [comment]
Well, that may be overstating it a bit. I think it just prefers that its the first line. In theory, you could still add params and the rest of the docblock... but generally, IDEs don't do this and most developers don't either as its duplicating the same documentation as the hook/alter.

Regardless, add this as an option would certainly be helpful at the very least. It's really loud for code that is based on different (antiquated) coding standards as a whole.

**Comment by mglaman** [comment]
My take wasn't phpdoc but rather return types and inline parameter types.

```
function mymodule_commerce_checkout_pane_info_alter(array &$definitions): void {
  
}
```

**Comment by mglaman** [comment]
@markcarver can you also post an example of the code? Just so we can document. It's not about coding standards, but the actual code in the parameters and return type.

**Comment by mglaman** [comment]
I think this is a won't fix, works as designed, until example code provided to show it's not about PHPDoc

**Comment by mglaman** [comment]
I'll see if there's a way to ignore return types if it is a Drupal hook implementation.

**Comment by verbruggenalex** [comment]
I think the smart choice is to not ignore the return types on Drupal hook implementations. Drupal hooks are called like this:

```php
        // Allow modules to alter widget actions.
        \Drupal::moduleHandler()->alter('paragraphs_widget_actions', $widget_actions, $context);
```

And then documented in the modules/contrib/paragraphs/paragraphs.api.php file like this:
```php
/**
 * Alter paragraphs widget.
 *
 * @param array $widget_actions
 *   Array with actions and dropdown widget actions.
 * @param array $context
 *   An associative array containing the following key-value pairs:
 *   - form: The form structure to which widgets are being attached. This may be
 *     a full form structure, or a sub-element of a larger form.
 *   - widget: The widget plugin instance.
 *   - items: The field values, as a
 *     \Drupal\Core\Field\FieldItemListInterface object.
 *   - delta: The order of this item in the array of subelements (0, 1, 2, etc).
 *   - element: A form element array containing basic properties for the widget.
 *   - form_state: The current state of the form.
 *   - paragraphs_entity: the paragraphs entity for this widget. Might be
 *     unsaved, if we have just added a new item to the widget.
 *   - is_translating: Boolean if the widget is translating.
 *   - allow_reference_changes: Boolean if changes to structure are OK.
 */
function hook_paragraphs_widget_actions_alter(array &$widget_actions, array &$context) {
}
```
If you duplicate and correct the information from the hooks at least phpstan will be able to check the code in the implemented hook. Phpstan does not know anything about the hooks in the api files.

**Comment by mglaman** [comment]
Correct. Properly type hint your hook implementations.

**Comment by stborchert** [comment]
Hm. The Drupal Coding Standards are very specific about that: https://www.drupal.org/docs/develop/standards/api-documentation-and-comment-standards#hookimpl
There is also an issue about this (https://www.drupal.org/project/coding_standards/issues/3056368) where some of the details are explained (e.g. "duplication of documentation").

**Comment by mglaman** [comment]
Nope! You don't need to do it in the phpDoc but with native PHP return type declarations.

**Comment by simesy** [comment]
I just wanted to clarify for future googlers, this is an example of hook_requirements that passes level 9 phpstan.

```
/**
 * Implements hook_requirements().
 */
function mymodule_requirements(string $phase): array {
   ...
```
