### ISSUE TITLE
PHP Warning - TestCase.php is not a file in phar

### ISSUE THREAD

**Issue by kerasai** [mglaman/phpstan-drupal#132]
I am receiving the following PHP warning when running PHPStan with the Drupal extension installed:

>PHP Warning:  file_get_contents(phar:///app/vendor/phpstan/phpstan/phpstan/vendor/phpunit/phpunit/src/Framework/TestCase.php): failed to open stream: phar error: "vendor/phpunit/phpunit/src/Framework/TestCase.php" is not a file in phar "/app/vendor/phpstan/phpstan/phpstan" in /app/web/core/tests/Drupal/TestTools/PhpUnitCompatibility/PhpUnit8/ClassWriter.php on line 43

I also end up with an empty file in `web/sites/simpletest/TestCase.php`.

This is a Composer-based install, Drupal `9.0.1`, and recent versions of everything. I'm running the PHPStan checks over custom code only--which there is very little at this time.

One more tidbit, not sure if it's normal/expected, is that the analysis runs for a long time (in comparison to the other checks). I'm on Lando, so there is certnaly a slowness factor involved. and the . The `phpstan-deprecation-rules`, `phpstan-strict-rules`, and `phpstan-phpunit` runs for 2-3 seconds total. When I add the Drupal checks, it takes ~20 seconds.

**Comment by mglaman** [comment]
HEAD is failing against Drupal 9. I'm trying to find time to sit down and go through it.

There were changes in how Drupal handles the wide range of PHPUnit versions it supports.

**Comment by mglaman** [comment]
#134 will help uncover bugs like this for Drupal 9

**Comment by mglaman** [comment]
So. This was a weird one with PhpUnit 8 support. 

Drupal tries to re-write TestCase for `setUp(): void` compatibility. See https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/tests/Drupal/TestTools/PhpUnitCompatibility/PhpUnit8/ClassWriter.php

This creates a file in `sites/simpletest/TestCase.php`.

**Comment by mglaman** [comment]
@kerasai can you try with https://github.com/mglaman/phpstan-drupal/releases/tag/0.12.9? I added a workaround for that file mutation to get tests to pass here.

**Comment by mglaman** [comment]
I think https://github.com/mglaman/phpstan-drupal/pull/175 may have fixed this, especially if you did not have PHPUnit in the project.
