### ISSUE TITLE
 Reflection error: Drupal\Tests\PhpunitCompatibilityTrait not found

### ISSUE THREAD

**Issue by MPParsley** [mglaman/phpstan-drupal#143]
**How is drupal-check installed?**

drupal-check is installed as a dependency to my project

**Environment:**
 - OS: macOS
 - PHP Version: 7.3
 - Drupal core: 9.0.x

**Describe the bug**
Reflection error occurs when using multiple arguments to test different files.
$ vendor/bin/drupal-check --deprecations --no-progress --drupal-root=../drupal --exclude-dir=vendor cookiebot_consent.module src/Event/LibrariesEvent.php

This issue was partially fixed in https://github.com/phpstan/phpstan/issues/3522 but still occurs when using different files as arguments.

cookiebot_consent.module
```
  $event = new LibrariesEvent($extension);
```

src/Event/LibrariesEvent.php
```
use Symfony\Contracts\EventDispatcher\Event;

class LibrariesEvent extends Event {
```

Symfony\Contracts\EventDispatcher\Event
```
namespace Symfony\Contracts\EventDispatcher;

use Psr\EventDispatcher\StoppableEventInterface;

if (interface_exists(StoppableEventInterface::class)) {
    class Event implements StoppableEventInterface
    {
    }
} else {
    class Event
    {
    }
}
```

**Console output**
```
 ------ -------------------------------------------------------------------- 
  Line   cookiebot_consent.module                                            
 ------ -------------------------------------------------------------------- 
         Reflection error: Psr\EventDispatcher\StoppableEventInterface not   
         found.                                                              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------- 
  Line   src/Event/LibrariesEvent.php                                        
 ------ -------------------------------------------------------------------- 
         Reflection error: Psr\EventDispatcher\StoppableEventInterface not   
         found.                                                              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  52     Reflection error: Psr\EventDispatcher\StoppableEventInterface not   
         found.                                                              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 
```

**Comment by mglaman** [comment]
#144 fixes the tests here and uncovers this bug

**Comment by mglaman** [comment]
So this path is covered in the autoloader provided by PHPStan Drupal.

```
		- /Users/ondrej/Downloads/drupal-check-issue/web/core/tests/Drupal/Tests/PhpunitCompatibilityTrait.php
```

\PHPStan\Drupal\DrupalAutoloader::addCoreNamespaces

```
        // Add core test namespaces.
        $core_tests_dir = $this->drupalRoot . '/core/tests/Drupal';
        $this->namespaces['Drupal\\BuildTests'] = $core_tests_dir . '/BuildTests';
        $this->namespaces['Drupal\\FunctionalJavascriptTests'] = $core_tests_dir . '/FunctionalJavascriptTests';
        $this->namespaces['Drupal\\FunctionalTests'] =  $core_tests_dir . '/FunctionalTests';
        $this->namespaces['Drupal\\KernelTests'] = $core_tests_dir . '/KernelTests';
        $this->namespaces['Drupal\\Tests'] = $core_tests_dir . '/Tests';
        $this->namespaces['Drupal\\TestSite'] = $core_tests_dir . '/TestSite';
        $this->namespaces['Drupal\\TestTools'] = $core_tests_dir . '/TestTools';
        $this->namespaces['Drupal\\Tests\\TestSuites'] = $this->drupalRoot . '/core/tests/TestSuites';
```

For some reason the modifications done to the autoloader cause this to break.

I wonder if its due to the trait having this line of code?

```
<?php

namespace Drupal\Tests;

use Drupal\TestTools\PhpUnitCompatibility\RunnerVersion;

// In order to manage different method signatures between PHPUnit versions, we
// dynamically load a compatibility trait dependent on the PHPUnit runner
// version.
if (!trait_exists(PhpunitVersionDependentTestCompatibilityTrait::class, FALSE)) {
  class_alias("Drupal\TestTools\PhpUnitCompatibility\PhpUnit" . RunnerVersion::getMajor() . "\TestCompatibilityTrait", PhpunitVersionDependentTestCompatibilityTrait::class);
}
```

Going down the debug train to see why the autoloader hacks provided here broke things

**Comment by MPParsley** [comment]
A similar issue existed with interface_exists in https://github.com/phpstan/phpstan/issues/3521

**Comment by mglaman** [comment]
@ondrejmirtes I'm trying to track down what's happening. Because the BetterReflection picks up the file.. kind of. (Made some screenshots in #145 )

But what I thought was interesting is this:

```
	scanDirectories:
		- '%drupal.drupal_root%/core/tests/Drupal/Tests'
	scanFiles:
		- '%drupal.drupal_root%/core/tests/Drupal/Tests/PhpunitCompatibilityTrait.php'
```

The trait error still occurs with a directory scan, but not with file scan.

**Comment by ondrejmirtes** [comment]
Weird, try to reproduce the issue with a vanilla PHPStan install, or in OptimizedDirectorySourceLocatorTest in phpstan-src...

**Comment by mglaman** [comment]
@ondrejmirtes 👍  will do. I'm trying to do some investigative work to see where/what/how. If it is in PHPStan's reflection code or the BetterReflection library.

**Comment by mglaman** [comment]
Merging the PR to get a conflict in so phpstan-drupal "works." The conflict is on `phpstan/phpstan:^ 0.12.43`.

Notes:

* the update of nikic/php-parser to 4.10.0 or ondrejmirtes/better-reflection to 4.3.29 (https://github.com/phpstan/phpstan-src/commit/ff092a0187555a3b0f79cc9b951e051c0253af59)
* ondrejmirtes/better-reflection:4.3.29 was just a bump to nikic/php-parser:4.10.0: https://github.com/ondrejmirtes/BetterReflection/commit/8221ddf8c466da7776a396fd47cb0bef27c70392
* Link to changes for php-parser: https://github.com/nikic/PHP-Parser/compare/v4.9.1...v4.10.0

I can't easily tell why. But I want to just get a green release out and then continue debugging.

**Comment by ondrejmirtes** [comment]
I think the conflicted release isn't necessary. Does this problem apply to all phpstan-drupal users? If not then you're blocking them from getting other useful stuff and bugfixes...

**Comment by mglaman** [comment]
@ondrejmirtes it unfortunately is, right now. Across the board, _all_ users are hitting reflection errors for `Drupal\Tests\PhpunitCompatibilityTrait`. This is my quick fix to stop getting pings/bug reports while I fix it.

It _could_ be fixed if I could have the `phpstan-drupal` extension affect the configuration to define `scanDirs` – since Drupal can have various vendor setups.

**Comment by mglaman** [comment]
Going to try the latest PHPStan. This fix stuck out at me

DependencyResolver - get current function reflection instead of obtaining it through ReflectionProvider (phpstan/phpstan-src@0e42941), #3909

**Comment by mglaman** [comment]
I found the error! It's due to an alias defined for PHPUnit compatibility between PHPUnit 6 and 7. I also double checked, it's not due to it being defined dynamically.

See: https://git.drupalcode.org/project/drupal/-/blob/8.8.x/core/tests/Drupal/Tests/PhpunitCompatibilityTrait.php#L10

```
```php
// In order to manage different method signatures between PHPUnit versions, we
// dynamically load a compatibility trait dependent on the PHPUnit runner
// version.
if (!trait_exists(PhpunitVersionDependentTestCompatibilityTrait::class, FALSE)) {
  class_alias("Drupal\TestTools\PhpUnitCompatibility\PhpUnit" . RunnerVersion::getMajor() . "\TestCompatibilityTrait", PhpunitVersionDependentTestCompatibilityTrait::class);
}
```

When I comment out that line of code and target the trait directly, non-aliased, everything works fine: ie `use \Drupal\TestTools\PhpUnitCompatibility\PhpUnit7\TestCompatibilityTrait;`.

When I modify the statement to be hardcoded and not rely on `RunnerVersion::getMajor()` it still breaks. So there is something about defining the trait alias that makes reflection break.
