### ISSUE TITLE
Add PHP8 support

### ISSUE THREAD

**Issue by chrfritsch** [mglaman/phpstan-drupal#150]
It's currently not possible to install this package on PHP8.

`
  [InvalidArgumentException]                                                                                                    
  Package mglaman/phpstan-drupal has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  
`

**Comment by mglaman** [comment]
This is probably blocked on https://github.com/mglaman/phpstan-drupal/issues/152

**Comment by wallon-ines** [comment]
it's work for me in PHP8 if add _is_string()_  in src/Drupal/DrupalAutoloader.php
```
                            if (is_string($argument)) {
                                $argument = str_replace('@', '', $argument);
                            }
```

**Comment by klausi** [comment]
I have disabled PHPStan testing on PHP 8 only for graphql in the meantime like so: https://github.com/drupal-graphql/graphql/blob/8.x-4.x/.github/workflows/testing.yml#L24

Now that the PR from above is merged maybe just a new release is missing? Or do you want to finish up your Drupal 9 testing first?

**Comment by vladivo** [comment]
@klausi as a workaround until next release you can require master branch:

```bash
composer require --dev --ignore-platform-req=php mglaman/phpstan-drupal:dev-master
```

**Comment by andypost** [comment]
The commited fix still not solving the issue, so I filed follow-up https://github.com/mglaman/phpstan-drupal/pull/163 

Basically container's YML-parser can return int/null/boolean but this helper only supposed to fix service names - strings that starts with `@`

Fixing it this way allowed to run upgrade_status on latest core and PHP 8

**Comment by mglaman** [comment]
I believe we can close this :)
