### ISSUE TITLE
phpstan-drupal should not conflict with phpstan/phpstan versions

### ISSUE THREAD

**Issue by klausi** [mglaman/phpstan-drupal#152]
Problem in composer.json:
```
    "conflict": {
        "phpstan/phpstan": "^0.12.43"
    },
```
Why is that necessary? It blocks me from upgrading PHPStan to any higher version.

**Comment by mglaman** [comment]
See `git blame` on `composer.json`, leads to here: https://github.com/mglaman/phpstan-drupal/pull/145

Blame Drupal's `PhpunitCompatibilityTrait` class/trait aliasing in D8. It was the quickest fix to prevent everything from being broken.

**Comment by mglaman** [comment]
This is the issue: https://github.com/mglaman/phpstan-drupal/issues/143

**Comment by mglaman** [comment]
Also see https://github.com/mglaman/phpstan-drupal/pull/149

**Comment by mglaman** [comment]
@klausi Found the problem! https://github.com/phpstan/phpstan/issues/4194

So PHPStan in its autoloader tries to verify a file and the startline for the PhpUnitCompatibility was mismatched. Hopefully, we can get the fix merged in and remove this conflict.

**Comment by klausi** [comment]
Cool, our workaround in phpstan.neon was to scan the file manually with this:
```neon
parameters:
	# PHPStan cannot find files in this test directory automatically.
	scanDirectories:
		- ../../core/tests/Drupal/Tests
```

**Comment by mglaman** [comment]
Yeah, it's weird. That works but not if you manually include the file. And there is no way for extensions to influence the `scanDirectories` parameter of the container. The container is already compiled before extensions are loaded.

**Comment by mglaman** [comment]
Okay, once https://github.com/nikic/PHP-Parser/issues/738 is resolved, PHPStan needs to use a release with that fix, then we're unblocked.

**Comment by mglaman** [comment]
@klausi see https://github.com/mglaman/phpstan-drupal/releases/tag/0.12.7 :) unblocked and no more trait bugs

**Comment by MPParsley** [comment]
Great work Matt!
