### ISSUE TITLE
Enable configuration of docroot

### ISSUE THREAD

**Issue by daFish** [mglaman/phpstan-drupal#16]
Right now the extension assumes you have either `docroot` or `web` as your docroot. However, in one of our instances we use `public_html` and cannot chance this for the time being.

It would be great if we could configure the used docroot. If someone can point to the right extension points I would be more than interested to contribute.

**Comment by mglaman** [comment]
Sounds like a good idea. It could be a parameter setting, instead of constantly adding different directories to check.
