### ISSUE TITLE
Add dynamic file load support for module_load_include

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#166]
Based on https://github.com/mglaman/phpstan-drupal/pull/158, it looks like the `Interface Translation` module adds `.batch.inc`, `.translation.inc`, and `.bulk.inc`.

We had LoadIncludes added for #124. This handles the module handler service with loadIncludes. We need a similar method to run `module_load_include` dynamic includes.

**Comment by mglaman** [comment]
Test would be analyzing locale.module

**Comment by mglaman** [comment]
While working on this, also review: https://www.drupal.org/project/drupal/issues/697946

**Comment by mglaman** [comment]
Need a rule that runs on a Func call not a Method call

```
    public function getNodeType(): string
    {
        return Node\Expr\MethodCall::class;
    }
```

**Comment by SpadXIII** [comment]
This looks good and a better way to handle #158 indeed. I noticed that it doesn't seem to handle loadInclude calls of the module handler, like  `\Drupal::moduleHandler()->loadInclude('locale', 'translation.inc');`

**Comment by mglaman** [comment]
Those are already handled in another rule

**Comment by mglaman** [comment]
Oh! That's definitely a bug. Can you open an issue @SpadXIII and I can pick it up on my next maintenance session?
