### ISSUE TITLE
Use stub files instead of Drupal as a dependency

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#185]
This project would be _a lot_ easier to maintain if we leveraged stub files for the automated testing.

They are documented here: https://phpstan.org/user-guide/stub-files

**Comment by neclimdul** [comment]
Stub files might be useful for filling in some typing problems for contrib and sites while core is working on support. It is going to be a while before core it runs into iterable typing at level 6 for example. Its also not great about documenting nullable stuff in older bits of code.

**Comment by mglaman** [comment]
Stubs don't replace autoloading but allow custom enhanced phpDoc. Closing this
