### ISSUE TITLE
Configuration parameters excludes_analyse and excludePaths cannot be used at the same time

### ISSUE THREAD

**Issue by stef-van-looveren** [mglaman/phpstan-drupal#193]
I get the following error when trying out drupal-check. I guess it is coming from PHPStan. 
```
bash$  drupal-check -a web/modules/custom/
Configuration parameters excludes_analyse and excludePaths cannot be used at the same time.

Parameter excludes_analyse has been deprecated so use excludePaths only from now on.
```

**Comment by stef-van-looveren** [comment]
This prevents me from using drupal-check on a D9.2 installation.

**Comment by stef-van-looveren** [comment]
Wrong repo, I filed it on drupal-check now.

**Comment by SOMERSOFTAndrewCrook** [comment]
The issue to do with the changes in extension.neon when commit https://github.com/mglaman/phpstan-drupal/commit/f80977b4479faab3700bec5ec488d61a4921b6fa#diff-c0eed1d1286633a549d491ece85cd721b01ea34037971a8f41cfa8cade5645b8 for #179 was introduced
