### ISSUE TITLE
Anonymous classes trigger errors with version 0.12.11

### ISSUE THREAD

**Issue by stephen-cox** [mglaman/phpstan-drupal#194]
Since the release of version 0.12.11 we're now seeing errors that look like: 

```
  ------ ------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_directories/src/Plugin/Block/ChannelSearchBlock.php  
 ------ ------------------------------------------------------------------------------ 
  87     Class                                                                         
         Drupal\localgov_directories\Plugin\Block\AnonymousClass01a859945ded72         
         cee689e1589045065e was not found while trying to analyse it -                 
         discovering symbols is probably not configured properly.                      
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols            
 ------ ------------------------------------------------------------------------------ 
```

An example of the code that triggers this error can be seen here: https://github.com/localgovdrupal/localgov_directories/blob/7877f4c15e164b8524df30a0db343865c3621d5e/src/Plugin/Block/ChannelSearchBlock.php#L87

We don't get these errors when pinning phpstan-drupal to version 0.12.10. We're using phpstan 0.12.92.

Are there changes in Drupal coding standards for this or is it an error?

**Comment by mglaman** [comment]
😱  well, that's odd. I don't know why anonymous classes would be causing autoload errors. PHPStan supports anonymous classes.

**Comment by mglaman** [comment]
I'm trying to discern what could have changed in 0.12.11 to cause this: https://github.com/mglaman/phpstan-drupal/compare/0.12.10...0.12.11

Is it because we bumped the minimum phpstan? 


```
-        "phpstan/phpstan": "^0.12.64",
+        "phpstan/phpstan": "^0.12.65",
```

Or maybe the new `PluginAnnotationContextDefinitionsRule` and `ConfigEntityConfigExportRule` break anonymous classes.

**Comment by mglaman** [comment]
Shoot, yep.

```
        $className = $node->name->name;
        $namespace = $scope->getNamespace();
        $reflection = $this->reflectionProvider->getClass($namespace . '\\' . $className);
        $implementsExpectedInterface = $reflection->implementsInterface($this->getExpectedInterface());
        if (!$implementsExpectedInterface) {
            return [];
        }
```

It tries to perform a reflection look up without making sure it isn't anonymous.  I thought the following check would be enough

```
        if ($node->name === null) {
            return [];
        }
```

**Comment by mglaman** [comment]
While reading this issue, https://github.com/nikic/PHP-Parser/issues/554, I found out why the `name === null` didn't work: PHPStan gives it a name.

**Comment by mglaman** [comment]
A new release will be rolling out shortly! Thanks for letting me know about the bug

**Comment by mglaman** [comment]
Release is out! Thanks for your patience: https://github.com/mglaman/phpstan-drupal/releases/tag/0.12.12

**Comment by stephen-cox** [comment]
@mglaman Many thanks for the quick fix on this.
