### ISSUE TITLE
Problem with $drupalRoot when vendor is outside of web root

### ISSUE THREAD

**Issue by rondog** [mglaman/phpstan-drupal#202]
I am running the upgrade_status module for drupal 8 which utilizes this library. I was having an issue where the PHPStan scan was failing with 

> UnexpectedValueException thrown in /Users/xxx/Sites/mysite/vendor/nette/finder/src/Utils/Finder.php on line 209 while loading bootstrap file /Users/xxx/Sites/mysite/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: RecursiveDirectoryIterator::__construct(/Users/xxx/Sites/mysite/core/includes): failed to open dir: No such file or directory

My issue is /Users/xxx/Sites/mysite/core/includes indeed DOES NOT exist because my vendor folder lives above docroot. If that path was correct, it would be /Users/xxx/Sites/mysite/docroot/core/includes

This got me investigating the package mglaman/phpstan-drupal. Specifically src/Drupal/DrupalAutoloader.php line 70.

$drupalRoot = $finder->getDrupalRoot(); which equates to /Users/xxx/Sites/mysite/

Then the code goes on to define $this->drupalRoot = $drupalRoot; so what I did was:

$this->drupalRoot = $drupalRoot . '/docroot'; (in my case) and this fixed the PHPStan error and it was able to check the modules successfully.

I also had to change line 80 from:
`$this->serviceYamls['core'] = $drupalRoot . '/core/core.services.yml';`
to
`$this->serviceYamls['core'] = $this->drupalRoot . '/core/core.services.yml';`

Not sure if this is configurable already. I did some searching on this issue queue and looks like you can change the path in a neon file, but I dont know where I define that, especially when this project is just a dependency of https://www.drupal.org/project/upgrade_status

**Comment by mglaman** [comment]
It looks like your root composer.json probably has `name: drupal/drupal`, try renaming it. See https://www.drupal.org/project/upgrade_status/issues/3229725

I'm going to close as it seems exactly the same. Feel free to reopen if I am wrong. Hopefully this fixes it quickly for you.
