### ISSUE TITLE
PHP Fatal error:  Cannot redeclare standard_form_install_configure_form_alter()

### ISSUE THREAD

**Issue by adi-wtag** [mglaman/phpstan-drupal#204]
I am using custom profile for one of my drupal site. And mysite.profile Implements two hooks. The first one is : 
```
function standard_form_install_configure_form_alter(&$form, FormStateInterface $form_state) {
  // Add a placeholder as example that one can choose an arbitrary site name.
  $form['site_information']['site_name']['#attributes']['placeholder'] = t('My site');
  $form['#submit'][] = 'standard_form_install_configure_submit';
}
```
But I am getting this error during  `composer analyse`.

```
PHP Fatal error:  Cannot redeclare standard_form_install_configure_form_alter() ( previously declared in web/core/profiles/standard/standard.profile:16 ) in mysite/mysite.profile
````
So far, I find this is the correct way to use custom profile and alter a hook. But why is it not working during code check ?

**Comment by mglaman** [comment]
@adi-wtag you should rename your hook from `standard_*` to `myprofile_*`

**Comment by mglaman** [comment]
I'm surprised it's working, given you're using a different extension's name. But that's probably because it's before the site is fully installed so _all_ hooks might be available.

**Comment by adi-wtag** [comment]
Renaming the hook works. Thanks @mglaman
