### ISSUE TITLE
Node::getRevisionAuthor deprecation not detected

### ISSUE THREAD

**Issue by timwood** [mglaman/phpstan-drupal#210]
**How is drupal-check installed?**

drupal-check is installed as a dependency to my project with composer

**Environment:**
 - OS: Linux
 - PHP Version: 7.3
 - Drupal core: 8.9

**Describe the bug**
`Node::getRevisionAuthor` was deprecated in favor of `RevisionLogInterface::getRevisionUser` and removed in Drupal 9.0.0. This was reported in change record https://www.drupal.org/node/3069750 and is also mentioned on https://api.drupal.org/api/drupal/core%21modules%21node%21src%21Entity%21Node.php/function/Node%3A%3AgetRevisionAuthor/8.9.x.

I also opened [an issue on the Drupal Upgrade Status module](https://www.drupal.org/project/upgrade_status/issues/3240139) on Drupal.org.

**Comment by mglaman** [comment]
I would update your functuon to replace `EntityInterface` with `NodeInterface`. Deprecation checks alone wouldn't warn this, but PHPStan running at level 0 or 1 probably would.

**Comment by mglaman** [comment]
Closing since the type hinting should fix, nothing much can be done in this library
