### ISSUE TITLE
Error: No Drupal service map was registered. when running Rector

### ISSUE THREAD

**Issue by FlorentTorregrosa** [mglaman/phpstan-drupal#212]
Originally reported in https://www.drupal.org/project/rector/issues/3243281

Drupal version 9.2.6
Drupal Rector version 0.11.3
PHPStan Drupal version 0.12.15

I saw that my CI scanning contrib module fails for Rector because of the following error:

<code>
 [ERROR] Could not process "app/modules/custom/views_merge_rows/views_merge_rows.module" file, due to:                  
         "No Drupal service map was registered.". On line: 19
</code>

Same error on all files scanned by Rector.

But the error message is from vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php

Thanks for any help.

**Comment by mglaman** [comment]
@FlorentTorregrosa could you update with the command run? Maybe it's somehow being booted up and I'll need to do a deep dive

**Comment by mglaman** [comment]
Shoot, I reproduced this https://github.com/mglaman/phpstan-drupal/runs/4098116750?check_suite_focus=true. I wonder if somehow the extension's `.neon` is causing return type extensions to still be loaded even though it's not analyzing.

```
	-
		class: mglaman\PHPStanDrupal\Type\ContainerDynamicReturnTypeExtension
		tags: [phpstan.broker.dynamicMethodReturnTypeExtension]
```

**Comment by mglaman** [comment]
I tagged 1.0.1, which will remove the throw of that exception and this should not be a problem. Can you try with the latest Rector and phpstan-drupal:1.0.1?

**Comment by FlorentTorregrosa** [comment]
Thanks @mglaman, unfortunately to test on the lastest Rector, I am stucked on https://github.com/palantirnet/drupal-rector/pull/184 before

**Comment by mglaman** [comment]
The drupal-rector PR was merged. I'm going to close this
