### ISSUE TITLE
Service mapping does not support shortcut services aliases

### ISSUE THREAD

**Issue by iLexN** [mglaman/phpstan-drupal#218]
Thank for your tool, help a lot.

before is using Drupal 8, some service define in services.yml with `autowire: true`.

after upgrade to Drupal 9, will cause error `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a            [error]
non-existent service`

as a result, added a alias like 
```
GuzzleHttp\Client: '@http_client'
Drupal\Core\Config\ConfigFactoryInterface: '@config.factory'
Drupal\Core\Messenger\MessengerInterface: '@messenger'
Drupal\Core\Logger\LoggerChannelFactory: '@logger.factory'
Drupal\Core\Logger\LoggerChannelFactoryInterface: '@logger.factory'
```

after added the class alias in services.yml solve the error. but cannot run the check.

i found that the error is below and cause by defining the  `class alias`
```
Error thrown in /var/www/drupal8/vendor/mglaman/phpstan-drupal/src/Drupal/DrupalAutoloader.php on line 191 while loading bootstrap file /var/www/drupal8/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: Cannot unset string offsets
```

the `$serviceDefinition` in `vendor/mglaman/phpstan-drupal/src/Drupal/DrupalAutoloader.php` is string (ie. `@http_client`), and not an array 
```
"class" => "Drupal\custom_eq\Services\NodequeueExportClient"
  "arguments" => array:2 [
    0 => "http_client"
    1 => "logger.factory"
  ]
```

**Comment by mglaman** [comment]
This might be related to #222. This did not support autowired services, since Drupal did not.

**Comment by mglaman** [comment]
It's simliar but not the same. We do not support shorthand aliasing.
