### ISSUE TITLE
Incorrect documentation link in deprecated service warning

### ISSUE THREAD

**Issue by alisonjo315** [mglaman/phpstan-drupal#221]
The deprecated service warning is great! (#209)

When I see it in upgrade status report (on my 8.9.19 site, I'm getting it for our favorite deprecated service,  `path.alias_manager`), the documentation link is wrong -- specifically, it's missing the last number:
> The "path.alias_manager" service is deprecated. Use "path_alias.manager" instead. See https://drupal.org/node/309208.
[<img src="https://user-images.githubusercontent.com/2660348/140432496-3fdb4809-7da6-4cc0-b199-cd8b03fcc637.png" width="500"/>](https://user-images.githubusercontent.com/2660348/140432496-3fdb4809-7da6-4cc0-b199-cd8b03fcc637.png)

Here's the correct link: https://www.drupal.org/node/3092086

----

To reproduce, run upgrade status report on a 8.9.19 site that has a project that uses `path.alias_manager` -- in my case, it's in our site theme's `.theme` file -- and then click the "local scan result" link that'll come up in the report.

----

I've got `mglaman/phpstan-drupal` version 0.12.15, `drupal/upgrade_status` version 3.11.0, `drupal/core` version 8.9.19.

**Comment by alisonjo315** [comment]
I have no proof, but it **_feels_** like the URL is getting truncated somehow?

The service info is retrieved dynamically from somewhere, right? -- but I can't find any mention of "309208" without the 6 at the end, anywhere in Drupal core.  (I ran `grep -r "309208" web/core/` locally, but [here's a search on GitLab](https://git.drupalcode.org/search?group_id=2&project_id=59858&repository_ref=8.9.x&scope=&search=309208&search_code=true&snippets=false) that's the same thing.)  So, after a lot of digging around [this project](https://github.com/mglaman/phpstan-drupal), the [upgrade_status project](https://git.drupalcode.org/project/upgrade_status), and Drupal core, my guess is that the link is getting truncated.  To be clear, while this theory is my best guess, it also sounds quite unlikely?

I tried to track down where/how the error message (in the scan results) is put together, but I struck out.  For example, I see [getDeprecatedDescription()](https://github.com/mglaman/phpstan-drupal/blob/e473354f31b403f53e570b12a10ac4e062c504ea/src/Drupal/DrupalServiceDefinition.php#L94) (used in [StaticServiceDeprecatedServiceRule.php](https://github.com/mglaman/phpstan-drupal/blob/ec08902aa72f9977675b0369ce42b86a094f9db2/src/Rules/Deprecations/StaticServiceDeprecatedServiceRule.php#L66), which was added in PR #209) -- it seems like `deprecationTemplate` is relevant, but I couldn't figure out how works.

Anyway, I really felt like I'd figure out what was going on, but that's as far as I got.

**Comment by mglaman** [comment]
Super weird. It gets set here: https://github.com/mglaman/phpstan-drupal/blob/main/src/Drupal/ServiceMap.php#L52-L54

I wonder if it's truncated on the CLI or if there is something weird happening when Upgrade Status parses the output

**Comment by alisonjo315** [comment]
@mglaman Great question!!!!  I don't know if this is exactly what you meant BUT, I checked upgrade_status via drush and the documentation link is there, in full.

```bash
$ drush upgrade_status:analyze mytheme

My Theme Name, --
Scanned on Fri, 11/05/2021 - 18:10

FILE: web/themes/mytheme/mytheme.theme

STATUS         LINE                           MESSAGE                           
--------------------------------------------------------------------------------
Check manually 95   The "path.alias_manager" service is deprecated. Use         
                    "path_alias.manager" instead. See                           
                    https://drupal.org/node/3092086                             

```

----

So maybe I should submit this as an issue for upgrade_status, right...?

**Comment by mglaman** [comment]
@alisonjo315 that's super weird. Open an issue in upgrade_status. It's something in this formatter code: https://git.drupalcode.org/project/upgrade_status/-/blob/8.x-3.x/src/ScanResultFormatter.php#L164

**Comment by alisonjo315** [comment]
Ok cool, will do, thank you!

**Comment by mglaman** [comment]
@alisonjo315 when you create the upgrade_status issue, can you post it here, as well? Just in case folks end up here somehow and not finding that issue

**Comment by alisonjo315** [comment]
> @alisonjo315 when you create the upgrade_status issue, can you post it here, as well? Just in case folks end up here somehow and not finding that issue

Definitely!

----

> @alisonjo315 that's super weird. Open an issue in upgrade_status. It's something in this formatter code: https://git.drupalcode.org/project/upgrade_status/-/blob/8.x-3.x/src/ScanResultFormatter.php#L164

I agree -- and, yesterday I spent way too much time looking at the parts of that file concerned with creating messages about deprecated _**functions**_ 🤦‍♀️ but, I agree it must be somewhere in there.

ACTUALLY, probably here, though I can't figure out how -- but like, it's gotta be...........
https://git.drupalcode.org/project/upgrade_status/-/blob/8.x-3.x/src/ScanResultFormatter.php#L223

Anyway, we'll see!
