### ISSUE TITLE
Add test for setting an empty field's first item to null

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#228]
Spinning from https://git.drupalcode.org/project/drupal/-/merge_requests/454#note_55009

Drupal.org issue: https://www.drupal.org/project/drupal/issues/3254966

```patch
-    $entity->field_test[0] = NULL;
+     $entity->field_test = NULL;
```

Without this fix, PHPStan crashes when running against Drupal core

```
Internal error: Internal error: Cannot assign an empty string to a string  
offset in file                                                             
/var/www/html/core/modules/link/tests/src/Kernel/LinkItemTest.php          
Run PHPStan with --debug option and post the stack trace to:               
https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md       
Child process error (exit code 1):
```

**Comment by mglaman** [comment]
It'd be great to analyze `core/modules/link/tests/src/Kernel/LinkItemTest.php` and test the EntityFieldsViaMagicReflectionExtension return type extension.

Full code example to test:

```
$entity = EntityTest::create();
$entity->field_test = ['uri' => 'internal:/node/add'];
$entity->field_test = [
  'uri' => 'internal:/node/add',
  'options' => ['query' => NULL],
];
$entity->field_test = 'internal:/node/add';
$entity->field_test[0] = NULL;
```

**Comment by mallezie** [comment]
This seems to be fixed in the lastest versions of phpstan / phpstan-drupal. So this issue can pobably be marked as fixed.

**Comment by mglaman** [comment]
Woo! thanks @mallezie.
