### ISSUE TITLE
Return type extension for static entity load and loadMultiple methods

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#229]
Entity objects have `::load` and `::loadMultiple` as a shortcut to the entity storage. However, the method is defined on `EntityBase` and returns `static`. We can use a return type extension to return the object type based on the calling class.

**Comment by brambaud** [comment]
#237 introduces tests to reproduce the issue.

It seems the return types are correctly infered.

**Comment by mglaman** [comment]
Closing this. #237 shows all works as expected!
