### ISSUE TITLE
Expand list of entity type storages

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#240]
I wanted to think of a great entry-level issue for someone new who wants to contribute to this project.

https://github.com/mglaman/phpstan-drupal/blob/main/extension.neon#L16-L19

I would love to expand the default list of known entity storages based on core entity types and major contrib.

All that needs to be done are additions to this map. For example, from this project's README:

```
        entityTypeStorageMapping:
            search_api_index: Drupal\search_api\Entity\SearchApiConfigEntityStorage
            search_api_server: Drupal\search_api\Entity\SearchApiConfigEntityStorage
```

**Comment by mglaman** [comment]
(I'd like this to remain open for a new contributor)

**Comment by ptt-homme** [comment]
I would love to help on this!

**Comment by mglaman** [comment]
Awesome, thanks!

**Comment by mglaman** [comment]
@ptt-homme I wanted to ping and see if you need any assistance? With #250, the parameter structure has changed. So you'll need to update any work based on the new mapping structure.

**Comment by brambaud** [comment]
A quick script to help building the mapping:

```php
<?php

use Nette\Neon\Neon;

/**
 * @file
 * Quick script to generate a entityMapping configuration of phpstan-drupal.
 *
 * You could use drush to tun it, for instance:
 * @code
 * $ drush php:script create-phpstan-drupal-entity-mapping.php
 * @endcode
 */

$entityMapping = [];

$definitions = \Drupal::entityTypeManager()->getDefinitions();

foreach ($definitions as $definition) {
  $entityMapping[$definition->id()] = [
    'class' => $definition->getClass(),
    'storage' => $definition->getStorageClass(),
  ];
}

$neon = Neon::encode(['entityMapping' => $entityMapping], true);

if (false === \file_put_contents(__DIR__ . '/entity-mapping.neon', $neon)) {
  throw new \RuntimeException('An error occurred when writing the neon config.');
}

```

**Comment by ptt-homme** [comment]
@mglaman ty for the alert!

@brambaud ty for the snippet.

I'll update my work based on the new mapping structure.

Have a nice sunday.
