### ISSUE TITLE
Problem with FieldItemListInterface::getValue() return not being falsy

### ISSUE THREAD

**Issue by neclimdul** [mglaman/phpstan-drupal#243]
I'm not positive this phpstan-drupal's fault but I can't recreate it in the phpstan sandbox. I got an odd error in a preprocess method on my theme. 

The code looks like this:
```php

    $image_src = $node->get('field_featured_image')->getValue();
    if (!empty($image_src)) {
      // Do some things and add the image.
    }
```

The error from phpstan:
```
409    Variable $image_src in empty() always exists and is not falsy.
```

The return type from getValue() is "mixed" which can be null/falsy but I can't get any combination of interfaces or inderection to recreate this in phpstan's sandbox so wondering if maybe there is some field magic in phpstan-drupal that might be causing a problem?

**Comment by neclimdul** [comment]
nvm, it had to do with the line directly above this. Someone wrote this for reasons I can't explain... 

```php
  if ($node->hasField('field_featured_image') && $node->get('field_featured_image')
      ->getValue()) {
    $image_src = $node->get('field_featured_image')->getValue();
    if (!empty($image_src)) {
```

so phpstan actually has a bug where it treats method calls as immutable when they can actually be mutable.

https://phpstan.org/r/e696e98e-e2b9-4fc3-ae5c-5b22dadc1a89

In this case my code is not great, phpstan just caught it by accident.

**Comment by mglaman** [comment]
@neclimdul I see, because `mixed` is not considered `mixed|null`. To PHPStan `mixed` means _some kind of value` but never `null`. I was going to say we should open an issue for it, but I'm not sure.

**Comment by neclimdul** [comment]
seems its a bit subtler problem and maybe by design? I'm discussing the issue here https://github.com/phpstan/phpstan/issues/6045
