### ISSUE TITLE
Make the discovered Drupal extensions accessible via a service

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#249]
We need to make the discovered extensions available from a service, just like ServiceMap.

This would help https://github.com/mglaman/phpstan-drupal/issues/247 and also improve the existing load include return type extensions.

**Comment by brambaud** [comment]
Should we enhance the existing `ExtensionDiscovery` and  `Extension` or should we create another service and/or another value object using them? 🤔

**Comment by mglaman** [comment]
Fixed via https://github.com/mglaman/phpstan-drupal/pull/264
