### ISSUE TITLE
Hint return type of entity ::access method

### ISSUE THREAD

**Issue by dpi** [mglaman/phpstan-drupal#272]
Should be able to hint the correct return type of `\Drupal\Core\Access\AccessibleInterface::access` depending on the value of `$return_as_object` parameter.

This interface is implemented by entities.

In the least, calling it on content entities should resolve, such that:

```
$result = $node->access($account, 'operation', FALSE);
assert(is_bool($result));
$result = $node->access($account, 'operation', TRUE);
assert($result instanceof \Drupal\Core\Access\AccessResultInterface);
```

**Comment by mglaman** [comment]
We also need to have a dynamic return type for `\Drupal\Core\Entity\EntityAccessControlHandlerInterface`
