### ISSUE TITLE
Unsafe usage of new static() in most of the Block and Form classes

### ISSUE THREAD

**Issue by renebakx** [mglaman/phpstan-drupal#275]
I'm not sure if this is 'fixable' within the scope of this specific rule Drupal rule set as it's technically not wrong, and perhaps more of an issue that belongs in the core issue queue than in this repository.

In Drupal Block and Form classed are created with the static create function as defined in ContainerFactoryPluginInterface
I've created an GIST of the situation with a Block as example.

see https://gist.github.com/renebakx/ace6767707c647d1ca854067b9f4148f

The issue is that  Drupal\Core\Block\BlockPluginTrait declares a __construct() and a lot of modules override the constructor and static create function to add extra services to their block.

Relevant information for the stack I use for this.

Stock Drupal 9.3 core and added the following lines to the require-dev and then ran phpstan with level 0 `phpstan analyze --level 0`

```
        "mglaman/phpstan-drupal": "^1",
        "phpstan/phpstan-deprecation-rules": "^1",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^1.2",
```

The error in question is 

```
 Unsafe usage of new static().                                                     
         💡 See: https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static  
```

**Comment by mglaman** [comment]
Unfortunately, PHPStan always displays this error. Drupal uses `new static` for extensibility. You'll need to manually ignore that error:

```
  ignoreErrors:
    - '#Plugin manager has cache backend specified but does not declare cache tags.#' # See - https://github.com/mglaman/phpstan-drupal/issues/112#issue-557001157
    - '#Unsafe usage of new static\(\)#' # See - https://github.com/mglaman/drupal-check/pull/187
    -  ```

**Comment by renebakx** [comment]
Thanks, that makes sense indeed, so I will need to create a .neon file after al to satisfy the CI checker on our custom modules!
