### ISSUE TITLE
Add common contrib entity types to mapping

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#278]
Thanks to @ptt-homme, all of Drupal core, Webform, Metatag, and Pathauto have their entity types mapped! 🥳 . I don't want to try and add mapping for "all the things" in this extension, as that is hard. But I think it'd be great to cover the more common contrib.

Contrib modules to add entity type mapping:

* [Paragraphs](https://www.drupal.org/project/paragraphs)
* [Redirect](https://www.drupal.org/project/redirect)

I can't really find any in the top beyond what has been added.

**Comment by mglaman** [comment]
Let's just add Paragraphs and Redirect. Anything else can be handled by adding documentation for https://github.com/mglaman/phpstan-drupal/issues/281 in the README

**Comment by ptt-homme** [comment]
Hi @mglaman 

Ok, i'll add this 2 buddy and have a look at #281 if I can help.

Merry Christmas

**Comment by mglaman** [comment]
I'm going to close this. I'd rather have modules add their mappings than keep trying to maintain them here. I merged https://github.com/mglaman/phpstan-drupal/issues/281 and even opened an issue for Paragraphs.
