### ISSUE TITLE
Render callbacks need to check if using a service name

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#296]
> @mglaman RenderCallbackRule has lots of false positive fwiw.
The user_toolbar() function. #lazy_builder supports '#lazy_builder' => ['user.toolbar_link_builder:renderToolbarLinks', []], this denotes a method on a service.

So we need to check if the string matched the signature of a service name and method

**Comment by dpi** [comment]
Unfortunately had to add a bunch of ignores for the recent updates :(.

**Comment by mglaman** [comment]
Could add the latest phpstan-drupal as a conflict to prevent it from being used. This is going to be fixed today though

**Comment by mglaman** [comment]
Core code for this concept: \Drupal\Core\Controller\ControllerResolver::createController

**Comment by dpi** [comment]
Thanks @mglaman!
