### ISSUE TITLE
RenderCallbackRule doesn't support 'non-empty-string' type and proper #lazy_builder callbacks

### ISSUE THREAD

**Issue by TMWagner** [mglaman/phpstan-drupal#301]
Given the method shown below, an error is thrown stating `#lazy_builder value 'non-empty-string' at key '0' is invalid.`

```
$content['stateful_cta'] = [
      // @fixme Test refactor. This is still causing problems.
      '#lazy_builder' => [static::class . '::lazyBuildCta', []],
      '#create_placeholder' => TRUE,
    ];
```    

I tested this code segment with three different ways of writing that logic. 

`$class_constant = __CLASS__;`
`$static_class = static::class;`
`$get_class = get_class();`

They all return exactly the same string. Only the code segment with `static::class;` throws the error

![image](https://user-images.githubusercontent.com/5316689/149179086-38c007ed-00b8-42c8-9012-87b86809fab8.png)

**Comment by mglaman** [comment]
At first I thought this was related to https://github.com/mglaman/phpstan-drupal/issues/296, but it's not. The class name plus `::` and method isn't being handled properly. It may be because PHPStan isn't handling `static::class` appropriately (or how we tell PHPStan to interpret it.)

It reads these fine:

```
            '\Drupal\pre_render_callback_rule\RenderArrayWithPreRenderCallback::preRenderCallback',
            '\Drupal\pre_render_callback_rule\NotTrustedCallback::unsafeCallback',
```

I'm working on phpstan-drupal today and will add this to the list. Thanks for reporting!

**Comment by mglaman** [comment]
I believe it's due to the `else` statement here for handling unknown types

https://github.com/mglaman/phpstan-drupal/blob/main/src/Rules/Drupal/RenderCallbackRule.php#L134-L137

**Comment by mglaman** [comment]
A fix is to use a proper callable:

```
- static::class . '::lazyBuildCta'
+ [static::class, '::lazyBuildCta']
```

**Comment by mglaman** [comment]
I just tagged https://github.com/mglaman/phpstan-drupal/releases/tag/1.1.8. It will still flag your current issue. But if you change it from `static::class . '::lazyBuildCta'` to `[static::class, 'lazyBuildCta']` it will report fine.

**Comment by TMWagner** [comment]
Thank you, @mglaman

**Comment by mglaman** [comment]
No problem! PHPStan is very particular around using `static` and it's basically best practice in Drupal (sometimes it's used when it's not needed). So it's a fun dance.
