### ISSUE TITLE
Extension service provider classes are not autoloaded.

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#31]
The pattern is camel case of the extension with ServiceProvider appended.

```
 ------ ------------------------------------------------------------------------- 
  Line   src/EntityReferenceRevisionsServiceProvider.php                          
 ------ ------------------------------------------------------------------------- 
         Class                                                                    
         Drupal\entity_reference_revisions\EntityReferenceRevisionsServiceProvid  
         er was not found while trying to analyse it - autoloading is probably    
         not configured properly.                                                 
 ------ ------------------------------------------------------------------------- 
```

**Comment by andypost** [comment]
Also missing 
- `.profile` & `.install` files
- permission providers, for ex `FieldUiPermissions`

**Comment by andypost** [comment]
Btw the same error I got when files were named differently https://www.drupal.org/project/styleguide/issues/3030381

**Comment by chrfritsch** [comment]
I tried to analyze the Thunder distribution and got this error for basically every class in the distro.

 ------ ----------------------------------------------------------------------------------------------
  Line   modules/thunder_media/tests/src/Functional/FileRemoveButtonTest.php
 ------ ----------------------------------------------------------------------------------------------
         Class Drupal\Tests\thunder\Functional\ThunderTestBase not found and could not be autoloaded.
 ------ ----------------------------------------------------------------------------------------------

 ------ ----------------------------------------------------------------------------------------------
  Line   modules/thunder_media/tests/src/Functional/FilenameTransliterationTest.php
 ------ ----------------------------------------------------------------------------------------------
         Class Drupal\Tests\thunder\Functional\ThunderTestBase not found and could not be autoloaded.
 ------ ----------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------
  Line   src/Annotation/ThunderOptionalModule.php
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------
         Class Drupal\thunder\Annotation\ThunderOptionalModule was not found while trying to analyse it - autoloading is probably not configured properly.
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------
  Line   src/Installer/Form/ModuleConfigureForm.php
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------
         Class Drupal\thunder\Installer\Form\ModuleConfigureForm was not found while trying to analyse it - autoloading is probably not configured properly.
 ------ -----------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by mglaman** [comment]
@chrfritsch ah yeah that's due to #24 which I need to tag a release for.

**Comment by mglaman** [comment]
@andypost that's to be expected

**Comment by chrfritsch** [comment]
Thanks @mglaman 👍

**Comment by andypost** [comment]
Thanks, confirm it works now

**Comment by jibran** [comment]
To ignore this you can add the following to `phpstan.neon`.
```yml
	excludes_analyse:
		# @todo Remove this after https://github.com/mglaman/phpstan-drupal/issues/31
		- *ServiceProvider.php
```

**Comment by claudiu-cristea** [comment]
@jibran but you probably don't want to ignore, you want to check this too.

**Comment by claudiu-cristea** [comment]
Drupal Extension allows to define Behat subcontexts in module's root as MODULENAME.behat.inc. But we are getting this:

```
 ------ ------------------------------------------------------------------------------------------------------------------------
  Line   joinup_core/joinup_core.behat.inc
 ------ ------------------------------------------------------------------------------------------------------------------------
         Class JoinupCoreSubContext was not found while trying to analyse it - autoloading is probably not configured properly.
 ------ ------------------------------------------------------------------------------------------------------------------------
```

I can workaround by adding those files in composer > autoloading  > classmap. But a generic fix would be better.

**Comment by jibran** [comment]
> @jibran but you probably don't want to ignore, you want to check this too.

@claudiu-cristea Yeah, for sure but until we have the fix we can ignore it so that the report can pass.

**Comment by eiriksm** [comment]
To those of you struggling with module service providers, please test and provide feedback in https://github.com/mglaman/phpstan-drupal/pull/86 :)
