### ISSUE TITLE
Improve performance of BrowserTestBaseDefaultThemeRule

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#318]
Spinning out from https://github.com/mglaman/phpstan-drupal/issues/316

When scanning `core/modules/action` which has 21 files analyzed, BrowserTestBaseDefaultThemeRule is invoked 19 times. Scanning the entire files only took 48.4s but that rule accounted for 23.8s seconds! That is 49.24% of the time.

![Screen Shot 2022-01-31 at 2 28 55 PM](https://user-images.githubusercontent.com/3698644/151868047-9e899af4-8703-40ff-878b-abaf3c5be75d.png)

I assume it has to be this first check to see if the class extends BrowserTestBase

```
       $classType = $scope->resolveTypeByName($node->namespacedName);
        assert($classType instanceof ObjectType);

        $browserTestBaseType = new ObjectType('Drupal\\Tests\\BrowserTestBase');
        if (!$browserTestBaseType->isSuperTypeOf($classType)->yes()) {
            return [];
        }
```

There needs to be a lighter preflight check besides digging into reflection.

**Comment by neclimdul** [comment]
Yeah, that's my fault actually. I wasn't sure if there was more you wanted to do on this merge so that merge... was to this merge

**Comment by neclimdul** [comment]
@mglaman i messed that merge up. I was targeting your other merge to show the diff and any other changes so its stuck out on the branch for your merge request.

**Comment by mglaman** [comment]
OH! That's why things didn't run!
