### ISSUE TITLE
Update list of deprecated global constants

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#326]
See https://api.drupal.org/api/drupal/deprecated/9.4.x?type=constant

We don't need to worry about class constants, only global ones:

* [DRUPAL_MINIMUM_PHP](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/constant/DRUPAL_MINIMUM_PHP/9.4.x)
* [DRUPAL_MINIMUM_PHP_MEMORY_LIMIT](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/constant/DRUPAL_MINIMUM_PHP_MEMORY_LIMIT/9.4.x)
* [DRUPAL_MINIMUM_SUPPORTED_PHP](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/constant/DRUPAL_MINIMUM_SUPPORTED_PHP/9.4.x)
* [DRUPAL_RECOMMENDED_PHP](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/constant/DRUPAL_RECOMMENDED_PHP/9.4.x)
* [FILE_INSECURE_EXTENSION_REGEX](https://api.drupal.org/api/drupal/core%21modules%21file%21file.module/constant/FILE_INSECURE_EXTENSION_REGEX/9.4.x)
* [FILE_STATUS_PERMANENT](https://api.drupal.org/api/drupal/core%21includes%21file.inc/constant/FILE_STATUS_PERMANENT/9.4.x)
* [PREG_CLASS_CJK](https://api.drupal.org/api/drupal/core%21modules%21search%21search.module/constant/PREG_CLASS_CJK/9.4.x)
* [PREG_CLASS_NUMBERS](https://api.drupal.org/api/drupal/core%21modules%21search%21search.module/constant/PREG_CLASS_NUMBERS/9.4.x)
* [PREG_CLASS_PUNCTUATION](https://api.drupal.org/api/drupal/core%21modules%21search%21search.module/constant/PREG_CLASS_PUNCTUATION/9.4.x)
* [REQUEST_TIME](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/constant/REQUEST_TIME/9.4.x)
* [SCHEMA_UNINSTALLED](https://api.drupal.org/api/drupal/core%21includes%21schema.inc/constant/SCHEMA_UNINSTALLED/9.4.x)
* 

The mapping needs to be updated in https://github.com/mglaman/phpstan-drupal/blob/main/src/Rules/Deprecations/AccessDeprecatedConstant.php#L44

**Comment by mallezie** [comment]
Added a pull request.

**Comment by mxr576** [comment]
By adding these deprecations to **a static list** that applies to _all Drupal versions_, basically, the downstream that runs Drupal < 9.3.0 got forced to lock `mglaman/phpstan-drupal` to a previous version otherwise the CI just keep failing.

Can we add these deprecations dynamically based on the Drupal version that the tool is being executed?

**Comment by mglaman** [comment]
Ah crud. I didn't think of that. Yes, we can do that.

**Comment by mglaman** [comment]
Okay, reopened so that the items added can be included based on version

**Comment by mglaman** [comment]
All right, merged in the check. I will be releasing an update with this soon.

**Comment by mxr576** [comment]
Super, thank you!
