### ISSUE TITLE
Rule for EntityTypeInterface::isSubclassOf() -> EntityTypeInterface::entityClassImplements()

### ISSUE THREAD

**Issue by catch56** [mglaman/phpstan-drupal#335]
Before:

```php
if ($entity_type->isSubclassOf(FieldableEntityInterface::CLASS)) {
```

After

```php
if ($entity_type->entityClassImplements(FieldableEntityInterface::CLASS)) {
```

CR here:  https://www.drupal.org/node/2842808

**Comment by mglaman** [comment]
We don't need to do anything, here. Since the method is deprecated on the interface (\Drupal\Core\Entity\EntityTypeInterface::isSubclassOf) PHPStan will pick it up.

Opened issue for Rector since that needs a Rule https://www.drupal.org/project/rector/issues/3266198
