### ISSUE TITLE
Rule for RevisionLogEntityTrait::getRevisionMetadataKey()

### ISSUE THREAD

**Issue by catch56** [mglaman/phpstan-drupal#336]
Deprecated in favour of ContentEntityTypeInterface::getRevisionMetadataKey()

https://www.drupal.org/node/2831499

**Comment by mglaman** [comment]
@catch56 Is there any specific reason why it was not deprecated in the phpDoc but only at runtime? 

```
  protected static function getRevisionMetadataKey(EntityTypeInterface $entity_type, $key) {
    @trigger_error(static::class . 'getRevisionMetadataKey() is deprecated in drupal:9.0.0 and is removed from drupal:10.0.0. Use $entity_type->getRevisionMetadataKey() instead. See: https://www.drupal.org/node/2831499', E_USER_DEPRECATED);
```

If the method had `@deprecated` it would be caught. I'm not sure if this was due to conflicts with calls to \Drupal\Core\Entity\ContentEntityType::getRevisionMetadataKey (a non-static method.)

**Comment by mglaman** [comment]
Closing, it's super outdated.
