### ISSUE TITLE
"CacheableJsonResponse does not have a constructor", but it's used in core with arguments

### ISSUE THREAD

**Issue by alberto56** [mglaman/phpstan-drupal#339]
Hi, I have the following code:

```
use Drupal\Core\Cache\CacheableJsonResponse;

...

  /**
   * Mockable wrapper around a cacheable JSON response with metadata.
   */
  public function cacheableResponse(array $result) : CacheableJsonResponse {
    $response = new CacheableJsonResponse($result['response']);
    $response->addCacheableDependency(CacheableMetadata::createFromRenderArray($result['cache']));
    return $response;
  }

```

and I have the following version of phpstan and php:

```
php --version
PHP 8.0.15 (cli) (built: Jan 26 2022 17:33:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
phpstan --version
PHPStan - PHP Static Analysis Tool 1.4.6
cat /var/www/html/composer.lock |grep mgla|grep source
                "source": "https://github.com/mglaman/phpstan-drupal/tree/1.1.10"

```

According to [this](https://api.drupal.org/api/drupal/core%21modules%21system%21tests%21modules%21system_test%21src%21Controller%21PageCacheAcceptHeaderController.php/function/PageCacheAcceptHeaderController%3A%3Acontent/8.2.x), CacheableJsonResponse can be (should be?) instantiated with an argument, and according to [this](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Cache%21CacheableJsonResponse.php/class/CacheableJsonResponse/8.2.x), addCacheableDependency() is actually a method of a trait of CacheableJsonResponse, however I'm getting:

```
 ------ -------------------------------------------------------------------- 
  Line   expose_status/src/Controller/ExposeStatusController.php             
 ------ -------------------------------------------------------------------- 
  57     Class Drupal\Core\Cache\CacheableJsonResponse does not have a       
         constructor and must be instantiated without any parameters.        
  58     Call to an undefined method                                         
         Drupal\Core\Cache\CacheableJsonResponse::addCacheableDependency().  
 ------ -------------------------------------------------------------------- 

```

I can't figure out how why I'm getting these errors, they seem wrong to me.

**Comment by mglaman** [comment]
That's very weird. Especially this:

```
Call to an undefined method                                         
         Drupal\Core\Cache\CacheableJsonResponse::addCacheableDependency().
```

It's like it did not analyze the parent or its traits. Very odd, I'll try to replicate and debug.

**Comment by alberto56** [comment]
Because I seem to be the only one experiencing this,I have dug deeper into this and did not manage to reproduce it in a new project outside of my code. It turned out that there was a namespace collision in the bootstrap file being used within the code I was tested: Drupal\Core\Cache\CacheableJsonResponse was being defined in a mock file for use with PHPUnit outside of Drupal, and that file was inadvertently being loaded with PHPStan.

This is therefore not a bug with PHPStan. 

Thanks nonetheless, I will close this ticket.

**Comment by mglaman** [comment]
Oh! Thanks for following up on the issue, I appreciate it!
