### ISSUE TITLE
Lazybuilder callback is expected wrongly to be array

### ISSUE THREAD

**Issue by Dropa** [mglaman/phpstan-drupal#371]
Following error appears if you try to
`drupal-check -a web/core/modules/big_pipe/tests/modules/big_pipe_test/src/BigPipeTestController.php`

```
  71     #lazy_builder value 'non-empty-string' at key '0' is invalid.         
         💡 Refactor concatenation of `static::class` with method name to an    
         array callback: [static::class, 'counter']  
```

Array callback however does not work on these cases.

In `\Drupal\Core\Render\PlaceholderGenerator::createPlaceholder` the callback is expected to be in string format.
as given part of the build array is passed as is into
```
Html::escape($callback) 
```

**Comment by mglaman** [comment]
I see. This seems like a bug in Drupal core.

```
    // Generate placeholder markup. Note that the only requirement is that this
    // is unique markup that isn't easily guessable. The #lazy_builder callback
    // and its arguments are put in the placeholder markup solely to simplify<<<
    // debugging.
    $callback = $placeholder_render_array['#lazy_builder'][0];
```

It seems the callback will be in Drupal's service callable format of `myservice.name:methodName`. Or a full `fooBar::method`.

Drupal core needs to fix the following:

```
  public function multiOccurrence() {
    return [
      'item1' => [
        '#lazy_builder' => [static::class . '::counter', []],
        '#create_placeholder' => TRUE,
      ],
      'item2' => [
        '#lazy_builder' => [static::class . '::counter', []],
        '#create_placeholder' => TRUE,
      ],
      'item3' => [
        '#lazy_builder' => [static::class . '::counter', []],
        '#create_placeholder' => TRUE,
      ],
    ];
  }
```

PHPStan cannot infer `static::class` in a string concatenation. Which means it needs an array callable, and the placeholder generate must support joining array callbacks.

This isn't a bug in phpstan-drupal but Drupal core.

**Comment by mglaman** [comment]
See https://www.drupal.org/project/drupal/issues/2977506

**Comment by Dropa** [comment]
I see, I originally did think it was Drupal bug, but since I didn't find any case where array callback would've been used and this was newly introduced error I thought to report it here first.

Great that you found that d.o issue, I'll check it on next week and create patch on it as I've pipeline standing due to this error :)

**Comment by mglaman** [comment]
Cool! I've got a MR up on that issue already. It converts the Big Pipe test controller as well, for proof.

**Comment by wimleers** [comment]
Reviewed that MR :)

**Comment by mglaman** [comment]
This will be fixed in https://github.com/mglaman/phpstan-drupal/pull/436, so `static` concat won't be reported.
