### ISSUE TITLE
getStorage->load for custom entity types reports type of Feed|null

### ISSUE THREAD

**Issue by dpi** [mglaman/phpstan-drupal#377]
When attempting to load an entity via getStorage for a custom entity type, PHPStan now thinks the entity returned is always going to be a `Drupal\aggregator\Entity\Feed|null`, instead of the custom entity type or something more generic.

Notes

 - entity type not mentioned as a custom class/storage in my `phpstan.neon`.
 - Aggregator (Feed) is not enabled, nor is it mentioned in the file with errors.
 - Only since 1.1.14, 1.1.13 does not have this issue

Code is roughly:

```php
protected EntityStorageInterface $myEntityStorage;

public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
  // ...
  $instance->myEntityStorage = $container->get('entity_type.manager')->getStorage('mycustomentity');
  return $instance;
}

public function doSomething($data): void {
  $entity = $this->myEntityStorage->load($data);
  if ($entity instanceof MyEntityType) { // <----- Error reported here
}
```

Error message:

>  Instanceof between Drupal\aggregator\Entity\Feed|null and Drupal\mymodule\Entity\MyEntity will always evaluate to false.

**Comment by brambaud** [comment]
It seems to me it comes from https://github.com/mglaman/phpstan-drupal/blob/479217bf286ef87aaff58c40ec762c868acfb3e8/src/Type/EntityStorage/EntityStorageDynamicReturnTypeExtension.php#L62

I reproduce also the issue on some projects but I did not succeed to reproduce it in phpstan-drupal tests 🤔

**Comment by mglaman** [comment]
Tried working on test, but hit some weird bugs where all of my methods returned `mixed` https://github.com/phpstan/phpstan/issues/6996

**Comment by dpi** [comment]
Thanks @mglaman !
