### ISSUE TITLE
Add new rule to mitigate possible misuse of an AccessResultInterface implementation in conditions

### ISSUE THREAD

**Issue by mxr576** [mglaman/phpstan-drupal#398]
Using an object as a condition that implements as `AccessResultInterface` is usually a human error and it the worst, it can lead to security issues. A new rule should warn about checking `if ($access) {}` instead of calling the appropriate method with bool return value on the object.

https://git.drupalcode.org/project/quick_node_clone/-/commit/ae0ee56a23a10b478e135957551bef1d5ed9f2b6

**Comment by mglaman** [comment]
I don't think we can handle this if folks are not using PHPStan level 6. We have _no idea_ if it is a boolean or object value. We have some support for the dynamic return type. See \mglaman\PHPStanDrupal\Type\AccessibleReturnTypeExtension

I don't know if PHPStan is respecting the return type below level 6. 

Also, the PHPDoc from Group module (seems like that is what it's for) maybe need a better `@return`. I don't know how we can handle this.

PHPStan should be warning about doing an `if()` on the access result object anyways warning that it's always true.

**Comment by mxr576** [comment]
Ahh, you are right, I have opened this issue too soon by saying the latest security announcements.

Level 2 https://phpstan.org/r/85659321-16d4-435c-a68e-0a5bd3608d46
Level 6 https://phpstan.org/r/1d654594-9cc6-4980-9a93-309840f5215b

**Comment by mxr576** [comment]
Actually just checked, level 4 is enough :grin: 
https://phpstan.org/r/2c273e51-82d5-4e4d-b0cc-88de86b9955f
