### ISSUE TITLE
Can your extension be used standalone on a module ?

### ISSUE THREAD

**Issue by CaptainQuirk** [mglaman/phpstan-drupal#40]
Hi,

I'm trying to use your extension for a specific module. Which means that I placed the `phpstan.neon` file at the root of my module, and not at the root of a complete drupal installation.
My module is a separate project, registered in a private composer index (satis) and has a specific continuous integration tunnel configured in gitlab. I need to be able to analyse the code standalone.

This is my configuration file : 

```
parameters:
	level: 7
includes:
	- vendor/phpstan/phpstan-phpunit/extension.neon
	- vendor/mglaman//phpstan-drupal/extension.neon
```

And this is the output of the `phpstan analyse src` command

```
ote: Using configuration file /app/phpstan.neon.
PHP Fatal error:  Uncaught TypeError: is_dir() expects parameter 1 to be a valid path, boolean given in /app/vendor/mglaman/phpstan-drupal/src/Drupal/ExtensionDiscovery.php:320
Stack trace:
#0 /app/vendor/mglaman/phpstan-drupal/src/Drupal/ExtensionDiscovery.php(320): is_dir(false)
#1 /app/vendor/mglaman/phpstan-drupal/src/Drupal/ExtensionDiscovery.php(139): PHPStan\Drupal\ExtensionDiscovery->scanDirectory('')
#2 /app/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php(83): PHPStan\Drupal\ExtensionDiscovery->scan('profile')
#3 /composer/vendor/nette/di/src/DI/Compiler.php(215): PHPStan\DependencyInjection\DrupalExtension->loadConfiguration()
#4 /composer/vendor/nette/di/src/DI/Compiler.php(175): Nette\DI\Compiler->processExtensions()
#5 /composer/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(306): Nette\DI\Compiler->compile()
#6 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#7 /composer/vendor/nette/di/src/DI/ContainerLoader.php(125): call_user_func_array(Arr in /app/vendor/mglaman/phpstan-drupal/src/Drupal/ExtensionDiscovery.php on line 320
```

When I remove your extension from the includes section, everything works as it should !

Thanks in advance !

**Comment by mglaman** [comment]
The includes are relative to the current directory they are in, not the tool. It makes sense but is kind of confusing. So you would need something like


../../.. I think

**Comment by CaptainQuirk** [comment]
Interesting. But this would not work in a continous integration service where there is no drupal installation around.

**Comment by mglaman** [comment]
Correct, it needs Drupal around. Otherwise it couldn't load the classes you're working with to analyze your codes usage. Like incorrect parameters or deprecated code

**Comment by CaptainQuirk** [comment]
Drupal core can very well be loaded as a dev dependency of a module. I'm using [autoload-drupal](https://github.com/fenetikm/autoload-drupal) for this.
There is no actual Drupal instance running, but I get a pretty good result with phpstan this way.

**Comment by mglaman** [comment]
I can already see some shortages in that package compared to the full autoloading required. Honestly I don't want to force adding something like that which would create bugs while Drupal is still generating namespaces. It's already stuck with it's quirks, that seems like it'd add more grief, possibly.

I do want to explore this and see what we can do. Honestly that package and something which swaps Drupal kernel would work. There's a lot of small things.

**Comment by mglaman** [comment]
FWIW I'd love to find a way to make this work. But Drupal.org is going to be using this on DrupalCI, so I want to be careful in any decisions.

**Comment by mglaman** [comment]
@CaptainQuirk okay, with #46 and #53 I have added a `drupal_root` parameter which lets you specify the Drupal root in the .neon file, and should solve some of these problems. Can you try using this to point to Drupal and fix autoloading? Hopefully, it's a decent fix for now.

**Comment by CaptainQuirk** [comment]
Hi !

Thanks for that ! I'll have a look as soon as I can

**Comment by Fonata** [comment]
@CaptainQuirk you can have a look at the [Nagios Monitoring module](https://drupal.org/project/nagios): it has PHPStan coverage for the Drupal 7 and 8 branches.

**Comment by mglaman** [comment]
This should work now with the `drupal.drupal_root` parameter. You _must_ have Drupal somewhere for this to work. Because your module will be interacting with its codebase.

```
parameters:
    drupal:
        drupal_root: /path/to/drupal
```

**Comment by mglaman** [comment]
You can also run PHPStan on DrupalCI following these instructions: https://www.drupal.org/docs/9/how-to-prepare-your-drupal-7-or-8-site-for-drupal-9/deprecation-checking-and-correction-tools#s-drupalorg-testing-support-for-deprecation-checking

There is a DrupalCI build step tool, however it only does deprecation testing: https://git.drupalcode.org/project/drupalci_testbot/blob/dev/src/DrupalCI/Plugin/BuildTask/BuildStep/CodebaseValidate/Phpstan.php

I'm going to close this as the original issue was about having phpstan.neon in the root of the module, not Drupal. And this is now capable by defining the path to Drupal.

Although, I don't know if the module would be discoverable properly if it is not within the Drupal codebase. For isntance, services mapping.
