### ISSUE TITLE
Add workflow to scan Drupal core

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#418]
* clone Drupal core
* run `composer require` to bump phpstan and phpstan-drupal
* run `composer install`
* run `cd core && ../vendor/bin/phpstan`

**Comment by mglaman** [comment]
This should be part of the release process

- draft release
- flow runs on draft
- prevent release of anything looks wrong

**Comment by Boegie** [comment]
This is exactly what I was thinking about today.

Especially useful when doing a smal bug-fix release. Useful for spot-checks when adding a new Rule.

**Comment by mglaman** [comment]
I'll add one. I didn't really want to make it a PR gate as I wasn't sure how long it'd take to run. Maybe it wouldn't be too bad if I had the caching action setup to reuse PHPStan caches.

I'll poke at it today to try and alleviate extra work/stress on Drupal core folks

**Comment by Boegie** [comment]
Not sure about the need for a nightly when there are no changes, maybe only on new/changed PRs?

**Comment by mglaman** [comment]
You're right, Drupal core will catch any breaks it introduces. This issue is pretty old, I think back when considering PHPStan was a new idea.

Retitled

**Comment by Boegie** [comment]
> I'll add one. I didn't really want to make it a PR gate as I wasn't sure how long it'd take to run. Maybe it wouldn't be too bad if I had the caching action setup to reuse PHPStan caches.

IIRC Drupal CI doesn't have caching, but running bleeding-edge of PHPStan makes it rather quick over there.
