### ISSUE TITLE
Missing Stub EntityInterface 

### ISSUE THREAD

**Issue by ophiocus** [mglaman/phpstan-drupal#423]
While running mglaman/drupal-check (1.3.1) against mglaman/phpstan-drupal (1.1.18) the following is registered.

Error: PHPDoc tag @extends has invalid type Drupal\Core\Field\FieldItemListInterface.
Error: Interface Drupal\Core\Entity\FieldableEntityInterface extends unknown interface Drupal\Core\Entity\EntityInterface.

This is in origin attributed to a missing stub for EntityInterface.

**Comment by mglaman** [comment]
The docs specify this error: https://phpstan.org/user-guide/stub-files

> Stub files are analysed independently from the rest of your codebase. This means that any type they’re referencing must also be present as a stub, even if you don’t want to override any of its PHPDocs.

But I have no idea why it isn't erroring in the CI :( Sorry about that!

**Comment by mglaman** [comment]
Made a new patch release with this fix: https://github.com/mglaman/phpstan-drupal/releases/tag/1.1.19
