### ISSUE TITLE
How to handle type inferencing for $entity->get('field_ref')->entity?

### ISSUE THREAD

**Issue by mrweiner** [mglaman/phpstan-drupal#464]
I've got a custom ContentEntity with the following:
```
  /**
   * {@inheritdoc}
   */
  public function getOrderItem(): ?OrderItemInterface {
    return $this->get('order_item')->entity;
  }
```

and PHPStan level 3 is spitting out
`Method Drupal\hc_commerce_transfer\Entity\CommerceTransferItem::getOrderItem() should return Drupal\commerce_order\Entity\OrderItemInterface|null but returns Drupal\Core\Entity\ContentEntityInterface. `

Is there a recommended way of handling this? All I can figure is to either use @phpstan-ignore or to add an ignore rule for the pattern, but those don't seem ideal.

**Comment by mglaman** [comment]
I usually use `// @phpstan-ignore-next-line` for this.

If it's not on a `return`, afterwards I use `/** @var **/` or `assert()`

**Comment by dpi** [comment]
Property annotations work well...

```php
/**
 * Node class.
 *
 * @property \Drupal\Core\Field\EntityReferenceFieldItemListInterface<\Drupal\node\Entity\Node> $someNodes
 */
final class Something extends Node {

  public const BUNDLE = 'something';

  public function foo(): ?Entity or array {
    // Use for singular
    $e = $this->someNodes->entity;
    // Use for multi cardinality
    $multiple = $this->someNodes->referencedEntities();
    \PHPStan\dumpType($e); // phpstan: Dumped type: Drupal\node\Entity\Node|null
    \PHPStan\dumpType($multiple); //phpstan: Dumped type: array<int, Drupal\node\Entity\Node>
  }

}
```

Bonus...

If you really want to force a type without assigning a var, dont add a $var to the inline.

```php

  public function foo(): int {
    $foo = 'not an int';
    /** @var int */
    return $foo;
  }
```

**Comment by mglaman** [comment]
Woah @dpi that's brilliant. Where should we log this? Should we have a generic "annotations" on https://www.drupal.org/docs/develop/development-tools/phpstan ? Or maybe "annotating fields"

**Comment by dpi** [comment]
Maybe a best practices or Common [cookbook/scenarios] page is due?

**Comment by mrweiner** [comment]
That's awesome. I thought I'd tried without a var like `/** @var int */` but I'll have to give it another go. 

I guess the only "downside" to the property annotation is needing to use the magic method `$foo->field` as opposed to `$foo->get('field')`, which feels wrong to me but is probably fine.
