### ISSUE TITLE
Add Support for deprecated drush/drush code

### ISSUE THREAD

**Issue by joshsedl** [mglaman/phpstan-drupal#486]
First off, I have to say that I love your work, Mr. Glaman!

I am currently on a Drupal module update-spree and having phpstan-drupal, the upgrade status module and drupal-rector makes my life so much easier!! So big thanks for that. :)

I just wanted to ask if there are any plans to also incorporate drush/drush code into this lovely tool! I was just updating a module, when I realized, that it uses deprecated Drush constants, mainly from "vendor/drush/drush/includes/bootstrap.inc", which is full of deprecated constants!

Furthermore, I am unsure, if this should be part of a seperate "phpstan-drush" repository, or part of phpstan-drupal, so feedback on this would be really helpful. :)

**Comment by mglaman** [comment]
Glad this tool helps you out so much!

When analyzing a module that provides Drush commands, it should detect using deprecated code from Drush automatically. The main magic of this package is to bring Drupal's stateful autoloading into a static autoloader. This package does run some of Drush's magic include file loading as well. If the module was using those constants, then PHPStan would report they couldn't be found if not in context.

What I think you might be encountering is our inability to reflect global constants.

See https://github.com/mglaman/phpstan-drupal/blob/main/src/Rules/Deprecations/AccessDeprecatedConstant.php

So you're right – a kind of `phpstan-drush` would be useful for tracking these. We could open an issue to replicate the `AccessDeprecatedConstant` rule for known Drush ones.

**Comment by weitzman** [comment]
Sounds good to me.

**Comment by joshsedl** [comment]
I agree!

**Comment by joshsedl** [comment]
I created a follow-up issue: https://github.com/mglaman/phpstan-drupal/issues/488! I guess we can close this then! :)
