### ISSUE TITLE
False negative accessCheck failure on non-chained entity queries

### ISSUE THREAD

**Issue by Boegie** [mglaman/phpstan-drupal#496]
Almost all problems with the `accessCheck` on entity queries are gone with #476.
Whilst working on https://www.drupal.org/project/drupal/issues/3330981 I've found a few escapees.

This one is about false negative `accessCheck` failure on entity queries that are _not_ chained.

I've added a test-case in the attached PR, it's probably more easily explained in code (and test failures) than words.

**Comment by mglaman** [comment]
Sounds like the opposite problem https://github.com/mglaman/phpstan-drupal/issues/388 was opened for, where extreme chaining things broke (I think.)

**Comment by mglaman** [comment]
Opened a discussion https://github.com/phpstan/phpstan/discussions/8773

I don't think this is possible because we cannot track side effects on objects.

**Comment by mglaman** [comment]
I am silly; https://phpstan.org/developing-extensions/type-specifying-extensions is the answer after all. I assumed not because I have only seen implementations that read the args.

**Comment by mglaman** [comment]
This was fixed with https://github.com/mglaman/phpstan-drupal/pull/497
