### ISSUE TITLE
Provide a dynamic return type for the service container.

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#5]
When fetching services, the return type is not correct. There should be a service map like https://github.com/phpstan/phpstan-symfony. This consumes the dumped container XML. We don't have that luxury.

Might need to resolve #4  first so we don't load every single services.yml

**Comment by Fonata** [comment]
Since this issue has a commit with a similar-sounding commit message: could we close this issue?

**Comment by mglaman** [comment]
Thanks, @Fonata. I can close.
