### ISSUE TITLE
Analyzing *.install: \Drupal::$container is not initialized yet

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#51]
\Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container.

**Comment by mglaman** [comment]
See #52.  Caused by `entity_test_update/entity_test_update.install` in `DbUpdatesTrait`

**Comment by jibran** [comment]
I don't think this is totally fixed. If you use `\Drupal` anywhere in your install file you'll see this error. For example 

```- ./vendor/bin/phpstan analyze web/modules/contrib/token --no-progress || if (($? == 255)); then false; else true; 
```
will fail. I'll create a PR to show the fail.

**Comment by jibran** [comment]
I created #66 but it didn't fail. I'll investigate more.
