### ISSUE TITLE
RoleStorage results integer IDs instead of string

### ISSUE THREAD

**Issue by andypost** [mglaman/phpstan-drupal#522]
Faced in https://www.drupal.org/project/drupal/issues/3348093#comment-14979770

Replacing in `core/modules/user/src/Form/RoleSettingsForm.php` following diff

```diff
-    $roles = user_role_names(TRUE);
+    $roles = $this->roleStorage->loadMultiple();
+    unset($roles[RoleInterface::ANONYMOUS_ID]);
    unset($roles[RoleInterface::AUTHENTICATED_ID]);
+    $roles = array_map(fn(RoleInterface $role) => $role->label(), $roles);
    $admin_roles = $this->roleStorage->getQuery()
```

caused 
```
  Line   core/modules/user/src/Form/RoleSettingsForm.php    
 ------ --------------------------------------------------- 
  62     Cannot unset offset 'anonymous' on array<int,      
         Drupal\user\Entity\Role>.                          
  63     Cannot unset offset 'authenticated' on array<int,  
         Drupal\user\Entity\Role>.   
```

**Comment by andypost** [comment]
So only static loading reports valid type

```diff
-    $roles = $this->roleStorage->loadMultiple();
+    $roles = Role::loadMultiple();
```

**Comment by mglaman** [comment]
What's the type hint for the storage property? Can you show that definition? I'm guessing PHPStan just reads it as inferred, a generic EntityStorageInterface and loses context because it's set in a constructor.

This is a known issue where our (phpstan-drupal) types get overridden when set to and fetched from a property

**Comment by andypost** [comment]
The role's storage defined as class https://github.com/mglaman/phpstan-drupal/blob/main/extension.neon#L181

but the form using `RoleStorageInterface`
```php
class RoleSettingsForm extends FormBase {

  /**
   * The role storage used when changing the admin role.
   *
   * @var \Drupal\user\RoleStorageInterface
   */
  protected $roleStorage;
```

**Comment by mglaman** [comment]
Okay, odd. The only thing would be if the interface isn't extending the normal config storage interface. Or we don't properly handle interfaces 

I'll debug this week.

**Comment by andypost** [comment]
Yes, it's defined as https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/user/src/Form/RoleSettingsForm.php#L17-19

**Comment by Kingdutch** [comment]
`ConfigEntityStorageInterface` extends `EntityStorageInterface` but doesn't alter `load` or `loadMultiple`

This is `EntityStorageInterface::load`
```
  /**
   * Loads one or more entities.
   *
   * @param $ids
   *   An array of entity IDs, or NULL to load all entities.
   *
   * @return \Drupal\Core\Entity\EntityInterface[]
   *   An array of entity objects indexed by their IDs. Returns an empty array
   *   if no matching entities are found.
   */
  public function loadMultiple(array $ids = NULL);
  ```

Any `type[]` is considered to be a "list", i.e. an array with numeric IDs.

So PHPStan(-Drupal) is working as intended in this case and it's Drupal core that's wrong unfortunately. Some part in the chain above `EntityStorageInterface` should have a more specific return type and `EntityStorageInterface::loadMultiple` should be `array<int|string, EntityInterface>`

**Comment by mglaman** [comment]
@Kingdutch but we have code to infer the proper type via a dynamic return type extension. It's just not working here for some reason.

**Comment by andypost** [comment]
Maybe instead of  check for `ConfigEntityStorageType` it should use interface?

**Comment by mglaman** [comment]
Correct. But it needs to do both. That type is specific internally
