### ISSUE TITLE
Add support for TrustedCallback attribute

### ISSUE THREAD

**Issue by fjgarlin** [mglaman/phpstan-drupal#527]
https://www.drupal.org/node/3274867 added the possibility of using the `TrustedCallback` on a method instead of having the whole class `...implements TrustedCallbackInterface`.

If new code uses this method `phpstan` checks fail like this:
```
41     #lazy_builder callback class 'Drupal\announcements_feed\LazyBuilders'  
         at key '0' does not implement                                          
         Drupal\Core\Security\TrustedCallbackInterface.                         
         💡 Change record: https://www.drupal.org/node/2966725.
```
(can be seen here https://www.drupal.org/pift-ci-job/2646296)

When debugging locally, Drupal code is happy with the new attributes.

The affected file is mostly https://github.com/mglaman/phpstan-drupal/blob/main/src/Rules/Drupal/RenderCallbackRule.php

**Comment by mglaman** [comment]
The new implementation

```
use Drupal\Core\Security\Attribute\TrustedCallback;

class SomeClass {
  #[TrustedCallback]
  public static function someCallback(...) {
  ...
  }
}
```

**Comment by fjgarlin** [comment]
Core checks the attributes like this:
```
if (!$safe_callback) {
   $method = new \ReflectionMethod($object_or_classname, $method_name);
   $safe_callback = (bool) $method->getAttributes(TrustedCallback::class);
}
```

**Comment by mglaman** [comment]
linking to my own change record triage issue https://github.com/mglaman/drupal-change-record-triage/issues/416
