### ISSUE TITLE
EntityQueryCountType is currently always expected to have knowledge about the Entity Query it is on.

### ISSUE THREAD

**Issue by Boegie** [mglaman/phpstan-drupal#545]
# Bug report
Every time an Entity Count Query is encountered., it is currently expected to have knowledge about the Entity Query it is acting on.

This means that there is currently no way an Entity Count Query can pass the "AccesCheck Test" when it is acting on an Entity Query that is unknown to PHPStan, so for example, comes from another function.

### Code snippet that reproduces the problem
See test cases in the PR #546, I hope they are more clear than my words above....

- `doCountInline` passes since there's knowledge about the Entity Query.
- `doQuery` passes, since PHPStan understands there's no knowledge about the Entity Query.
- `doCount` fails, since PHPStan doesn't understand there's no knowledge about the Entity Query, but still expects it passes the  "AccesCheck Test".

**Comment by mglaman** [comment]
I really dislike this `accessCheck` change for Drupal 10. _Really._

It looks like in `execute` we handle this the same way:

```
        if ($methodName === 'execute') {
            if (!$varType instanceof EntityQueryType) {
                return $defaultReturnType;
            }
```

So I guess all we can do is the same on counts.
