### ISSUE TITLE
Misses "Calling a static element on a trait" PHP 8.1 depreciation

### ISSUE THREAD

**Issue by ProCycleDev** [mglaman/phpstan-drupal#569]
**How is drupal-check installed?**

drupal-check is installed as a dependency to my project

**Environment:**
 - OS: Ubuntu Linux
 - PHP Version: 8.1
 - Drupal core: 9.4.x

**Describe the bug**
Using `drupal-check -d module/` does not catch a PHP 8.1 depreciation that is displayed on the website
Error is:
```
Deprecated function: Calling static trait method Drupal\commerce_customer_browser\Form\EntityBrowserFormTrait::getEntityIds is deprecated, it should only be called on a class using the trait in Drupal\commerce_customer_browser\Form\EntityBrowserFormTrait::validateEntityBrowserForm()
```
This is not a published module (yet). I was calling a static method from a Trait inside a form hook in the .module file of the module. This was depreciated in PHP 8.1.

See: https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.static-trait

**Console output**
Paste the output of the console when running the command with `-vvv`

```
Performing deprecation checks
Analyzing path: /srv/www/default/modules/commerce_customer_browser
Current working directory: /srv/www/default
Using Drupal root: /srv/www/default/web
Using vendor root: /srv/www/default/vendor
Assumed running as global dependency
PHPStan path: /srv/www/default/vendor/phpstan/phpstan/phpstan.phar
PHPStan configuration path: /tmp/drupal_check_phpstan_1675291111.neon
PHPStan configuration:
parameters:
	tipsOfTheDay: false
	reportUnmatchedIgnoredErrors: false
	excludePaths:
		- */tests/Drupal/Tests/Listeners/Legacy/*
		- */tests/fixtures/*.php
		- */settings*.php
		- */node_modules/*

	ignoreErrors:
		- '#\Drupal calls should be avoided in classes, use dependency injection instead#'
		- '#Plugin definitions cannot be altered.#'
		- '#Missing cache backend declaration for performance.#'
		- '#Plugin manager has cache backend specified but does not declare cache tags.#'
		- '#Unsafe usage of new static\(\)#'

	drupal:
		drupal_root: /srv/www/default/web

	level: 2
	bootstrapFiles:
		- /srv/www/default/vendor/mglaman/drupal-check/error-bootstrap.php


Executing PHPStan
 2/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%  1 sec/1 sec 

Result cache is saved.

 [OK] No errors                                                                 

Used memory: 211.59 MB
Finished executing PHPStan
Unlinking PHPStan configuration
Return PHPStan exit code
Thanks for using drupal-check!
```

**Comment by mglaman** [comment]
I tried to get PHPStan support for this, but it's hard https://github.com/phpstan/phpstan/issues/5782

And then that is for known callables, not ones within render arrays. phpstan-drupal is getting close to validating those, but wouldn't catch this specific error, yet.

**Comment by mglaman** [comment]
PHPStan 11 will support this!

**Comment by mglaman** [comment]
According to https://github.com/phpstan/phpstan-src/pull/2420 it should be supported/detected as of PHPStan [1.10.22](https://github.com/phpstan/phpstan-src/releases/tag/1.10.22).
