### ISSUE TITLE
Detect deprecated 10.0 hook_field_widget hooks

### ISSUE THREAD

**Issue by KalleVuorjoki** [mglaman/phpstan-drupal#599]
# Feature request

https://www.drupal.org/node/3180429 is the only hook deprecated from 9.5.x->10.0.
This is closely related to #126, but I think the proposed solution might be too resource intensive given that there's only single deprecated core hook.
I've used `grep -Eir 'field_widget_multivalue|_field_widget_form_alter|field_widget_WIDGET_TYPE' *` to manually search for the deprecated hook, but would be might be beneficial to automate this task.

**Comment by mglaman** [comment]
This is a PHPStan rules which needs to target PhpParser\Node\Stmt\Function_ and check if it's name matches this pattern.

Maybe it could be a configurable rule to help support other deprecated hooks more easily

**Comment by mglaman** [comment]
I'm going to close this for https://github.com/mglaman/phpstan-drupal/issues/126 which will handle detecting hooks based on my above comment. But be flexible enough for all future deprecations.
