### ISSUE TITLE
Custom field property with the name 'date' cannot be found

### ISSUE THREAD

**Issue by bkline** [mglaman/phpstan-drupal#602]
# Bug report

In a custom field with four properties, named `date`, `type`, `amount`, and `mileage` the code scan complains that the `date` property is undefined, but does not have a problem with the other three properties.

### Code snippet that reproduces the problem

```php
  public function toString(): string {
    $date = $this->date;
    ...
  }
```

### To reproduce:

1. `cd /tmp`
2. `composer create-project drupal/recommended-project phpstan-repro`
3. `cd phpstan-repro`
4. `composer require --dev mglaman/phpstan-drupal`
5. `tar -xf phpstan-drupal-repro.tgz # use attached tar file below`
6. `vendor/bin/phpstan analyze -c phpstan.neon`

### What you'll see

![image](https://github.com/mglaman/phpstan-drupal/assets/1634628/98c4b66e-a1c7-4a74-b7d1-ea7084d05ddf)

### File for step 5 
[phpstan-drupal-repro.tgz](https://github.com/mglaman/phpstan-drupal/files/12501237/phpstan-drupal-repro.tgz)

**Comment by mglaman** [comment]
Here's the "problem": Drupal has magical `__get` that map `$this->date` to the property defined in `propertyDefinitions`. It's valid code, but we need to expand https://github.com/mglaman/phpstan-drupal/tree/main/src/Reflection to handle that.

The "quick fix" is to use PHPDoc with `@property`.


```
/**
 * Repro field.
 *
 * @FieldType(
 *   id = "repro_field_for_phpstan"
 * )
 * @property string $date
 */
```

This documents the magical property for PHPStan. We had to provide stubs to add Drupal core support https://github.com/mglaman/phpstan-drupal/blob/main/stubs/Drupal/file/Plugin/Field/FieldType/FileItem.stub

I don't know why it's only erroring on this property, though, and not the others. That's confusing to me.

**Comment by bkline** [comment]
Thanks! Way too much magic in Drupal. 🧙‍♂️😭

**Comment by mglaman** [comment]
I'm going to close. I can't think of a great way to solve. It's on PHPStan's docs for `__get` setups: https://phpstan.org/writing-php-code/phpdocs-basics#magic-properties

Maybe it's a good candidate to put on the docs  https://www.drupal.org/docs/develop/development-tools/phpstan about custom field type properties.
