### ISSUE TITLE
Forbid usage of uniqid()

### ISSUE THREAD

**Issue by mondrake** [mglaman/phpstan-drupal#604]
# Feature request

In https://www.drupal.org/project/drupal/issues/2972100 we are discussing to replace usage of `uniqid()` across core.
If that’s accomplished, it’s worth having a static analysis check that it not regressing.

**Comment by mglaman** [comment]
This seems like it should be a custom rule and would live in its own package, such as forbidden functions. Drupal core could provide this rule and register it itself.

**Comment by mglaman** [comment]
I commented on https://www.drupal.org/project/drupal/issues/2972100#comment-15248168. This one feels a bit too opinionated for this package.
