### ISSUE TITLE
Add PHP 8.2 to test workflow

### ISSUE THREAD

**Issue by Boegie** [mglaman/phpstan-drupal#624]
# Feature request

In https://www.drupal.org/node/3397110 Drupal core bumped the recommended minimal PHP version from 10.2 upwards to PHP 8.2.
Let's include that in the test workflow.

**Comment by Boegie** [comment]
My proposal (and PR) would be to test 10.x on PHP 8,1 and 8.2 do 11.x only on PHP 8.2.

**Comment by Boegie** [comment]
Looking at the `build_integration_no_phpunit` job, shouldn't that have a `drupal "^10.0"` with `PHP 8.1` (and now `8.2`) sub-job?

**Comment by mglaman** [comment]
Huh, yeah. `build_integration_no_phpunit` is missing a D10 job entirely.

**Comment by mglaman** [comment]
Same with `build_integration` it seems.
