### ISSUE TITLE
Including api.php in DrupalAutoloader throws PHP redeclare error

### ISSUE THREAD

**Issue by peterwcm** [mglaman/phpstan-drupal#640]
# Bug report

In the latest 1.2.3, changes were made to the `DrupalAutoloader.php` to include `.api.php` files: https://github.com/mglaman/phpstan-drupal/commit/446a99004db28b5d711d9e834f0818c427f5be40

This causes a PHP error we can't fix or ignore because it's between the core `field` module and the contrib `tmgmt_content`. Both modules include the same hook example in their API file so requiring those files will throw a PHP Fatal error.

```
PHP Fatal error:  Cannot redeclare hook_field_info_alter() (previously declared in /projects/site/web/core/modules/field/field.api.php:53) in /projects/site/web/modules/contrib/tmgmt/sources/content/tmgmt_content.api.php on line 47
Fatal error: Cannot redeclare hook_field_info_alter() (previously declared in /projects/site/web/core/modules/field/field.api.php:53) in /projects/site/web/modules/contrib/tmgmt/sources/content/tmgmt_content.api.php on line 47
```

**Comment by mglaman** [comment]
Huh. The file should be loaded with a catch for even fatal errors. 

That module needs to be fixed.

**Comment by peterwcm** [comment]
Fatal errors cannot be caught as far as I know so I don't think you can work around that easily. While we can 'fix' the contrib module by adding a patch to have that hook commented, it might not make sense to the contrib maintainers.

From my understanding, api.php file is more of a documentation piece for custom hooks or related hook usage that's related to the module. They are just code examples and it's not meant to be included by others so logically it's not an issue from their end. What do you think?

**Comment by eiriksm** [comment]
Just to note, this is the case for many other contrib modules. Usually because they somewhat do not follow conventions in the api.php file, but even still. It's a documentation piece of a file, so it's kind of annoying.

Here is just a couple I experienced this morning:

```
Fatal error: Cannot redeclare elasticsearch_helper_aws_elasticsearch_helper_client_builder_alter() (previously declared in /__w/nymedia_commerce_profile/nymedia_commerce_profile/web/modules/contrib/elasticsearch_helper/elasticsearch_helper_aws/elasticsearch_helper_aws.module:17) in /__w/nymedia_commerce_profile/nymedia_commerce_profile/web/modules/contrib/elasticsearch_helper/elasticsearch_helper.api.php on line 19
```

```
Fatal error: Cannot redeclare ckeditor_media_embed_ckeditor_media_embed_object_alter() (previously declared in /__w/store/store/drupal/modules/contrib/ckeditor_media_embed/ckeditor_media_embed.module:136) in /__w/store/store/drupal/modules/contrib/ckeditor_media_embed/ckeditor_media_embed.api.php on line 21
```

**Comment by eiriksm** [comment]
To add to this: https://github.com/eiriksm/phpstan-drupal/pull/2 is a PR I created against my own fork, which demonstrates the bug. A redeclaration in an api.php file does not cause any issues in running a drupal site, but it totally crashes phpstan here :v:

**Comment by eiriksm** [comment]
Tried a couple of hacks to catch such a fatal error, but came up short. Seems like we should either

- Revert the commit
- or make it either opt-in or possible to opt out

**Comment by eiriksm** [comment]
Added a PR to be able to opt out of loading `api.php` files here: #641

**Comment by mglaman** [comment]
Sorry about this. I didn't think folks had that broken of `.api.php` files. I like the idea of opting out.

I'm going to rework your PR @eiriksm. I want to establish a bleeding-edge concept like in PHPStan. New rules are added as off by default, but including that file will enable them.

**Comment by eiriksm** [comment]
Wow you are the most kind, knowledgeful maintainer ever :heart: I have a feeling you more or less posted this just after waking up, so taking the time here to appreciate your work and a new release breaking stuff just highlights the impact of your work. Thank you, Matt!
