### ISSUE TITLE
Have AccessResult forbiddenIf and allowedIf perform truthy checks

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#734]
# Feature request

PHPStan does checks on `if` statements to verify they're evaluating `true` or `false` and if the condition is always true or false.

It'd be great to recreate that rule for `\Drupal\Core\Access\AccessResult::allowedIf` and `\Drupal\Core\Access\AccessResult::forbiddenIf`

**Comment by Kingdutch** [comment]
Documenting the conversation we had about this on Slack in case anyone comes across this and wants to pick this up :D 

The easiest way I see to achieve this is to make sure PHPStan can apply the existing rules for `if` statements which tell you if something is always TRUE or FALSE. This is done by `MatchExpressionRule` which is applied to any `MatchExpressionNode`.

The way to get `MatchExpressionRule` to apply to our `allowedIf`/`forbiddenIf` function calls then is to make sure we tell PHPStan that the arguments to those functions are a `MatchExpressionNode`. This can be done by implementing a `TypeNodeResolver` which tells PHPStan this exact information. [PHPStan documents how TypeNodeResolvers work](https://phpstan.org/developing-extensions/custom-phpdoc-types).

There is a good example of a type node resolver in PHPUnit which has three different extensions such as [AssertMethodTypeSpecifyingExtension](https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Type/PHPUnit/Assert/AssertMethodTypeSpecifyingExtension.php) which proxies to [AssertTypeSpecifyingExtensionHelper](https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Type/PHPUnit/Assert/AssertTypeSpecifyingExtensionHelper.php) that contains the actual logic of determining which node to return. The goal of that PHPUnit extension is to make calls to functions like `assert` behave like the underlying PHP built-in function or type which in turn lets PHPStan apply the relevant rules to the `assert*` methods as if they were native functions 🤩 

For example [`assertIsArray` proxies to `is_array`](https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Type/PHPUnit/Assert/AssertTypeSpecifyingExtensionHelper.php#L195) and [`assertIsNotArray` does the same with a `BooleanNot` around the result of `assertIsArray`](https://github.com/phpstan/phpstan-phpunit/blob/1.4.x/src/Type/PHPUnit/Assert/AssertTypeSpecifyingExtensionHelper.php#L125).

**Comment by mglaman** [comment]
Okay, I dug into this a bit and I'm not sure we can make it work _exactly_ this way. `\mglaman\PHPStanDrupal\Type\AccessResultConditionTypeSpecifyingExtension::specifyTypes` requires an array of expressions. `MatchExpressionNode` is not an expression.

I opened a draft PR for now.

**Comment by mglaman** [comment]
Opened https://github.com/phpstan/phpstan/discussions/10762 for some insight

**Comment by mglaman** [comment]
I think the type specifying extension was the wrong route. We should check the static method call for `AccessResult` and `allowedIf` or `forbiddenIf` and then take the first argument and inspect. But I wonder if that's too late and its no longer a binary operation because it's been converted to a boolean.

**Comment by mglaman** [comment]
@Kingdutch check out https://github.com/mglaman/phpstan-drupal/pull/737, about 1/2 way there
