### ISSUE TITLE
LockBackendInterface::acquire() is impure

### ISSUE THREAD

**Issue by longwave** [mglaman/phpstan-drupal#735]
# Feature request

```
$lock = \Drupal::lock();
if (!$lock->acquire('lock')) {
  $lock->wait('lock');
  if (!$lock->acquire('lock')) {
    throw new \RuntimeException('Could not acquire lock');
  }
}
```

outputs "Negated boolean expression is always true" for the second call to `$lock->acquire()`, because PHPStan assumes it is a pure function (the same inputs return the same outputs). But that is not true when acquiring a lock, so we should mark it as impure. This could be done in core or a stub file, and I figured it would be easier to land here first.

See https://phpstan.org/blog/remembering-and-forgetting-returned-values for more information.

**Comment by mglaman** [comment]
I tried testing this and couldn't find a great way. So I stubbed it out in the PHPStan playground: https://phpstan.org/r/f54b1740-e55d-4040-b773-808672a620f0

Adding `@phpstan-impure` didn't seem to fix the problem. But it does seem to work if the logic is removed from the conditional. So I'm not sure the best fix here. Maybe there needs to be a PHPStan issue.

**Comment by mglaman** [comment]
Ah... because in that example we had a concrete instance. See https://phpstan.org/r/7cbb6059-2ab6-4a4a-8c6f-f21626b8f8c0
