### ISSUE TITLE
Support turning off @internal check

### ISSUE THREAD

**Issue by bbrala** [mglaman/phpstan-drupal#747]
# Feature request

Bot is keeping many many pacltches back because of the @internal checkt. Would be nice to be able to disable that one.

**Comment by goba** [comment]
For the sake of the bot this landed in Upgrade Status in https://www.drupal.org/project/upgrade_status/issues/3445307

**Comment by goba** [comment]
Released in https://www.drupal.org/project/upgrade_status/releases/4.3.2
