### ISSUE TITLE
Stop testing PHP 7.4, 8.0 and Drupal 9

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#760]
Managing this project would be much easier if PHP 7.4 and PHP 8.0 were dropped. This would also stop Drupal 9 testing; or a Drupal 9 job could be created with PHP 8.1.

webflo/drupal-finder was raised to PHP 8.1 in its 1.3 release. I'm afraid it'll get more complicated with D11, PHPUnit 10/11.

Proposal: 

- bump minimum PHP version to PHP 8.1
- drop testing D9
- drop lower versions of Drush, etc, which allowed D9 testing

this would trigger the 1.3.0 release

**Comment by markdorison** [comment]
This makes sense to me. 👍🏻

**Comment by andypost** [comment]
PHP 8.1 is only supported next 1.5 years 
D9 surely needs phase out

**Comment by mglaman** [comment]
PHP bumped to 8.1. Technically D9 can be supported, if it was removed the following tests/rules could be dropped:

- AccessDeprecatedConstantTest, and probably \mglaman\PHPStanDrupal\Rules\Deprecations\AccessDeprecatedConstant
- \mglaman\PHPStanDrupal\Tests\Rules\ClassExtendsInternalClassRuleTest::testRule ContentEntityDeleteForm test case
- ConditionManagerCreateInstanceContextConfigurationRuleTest (and probably its rule)
- \mglaman\PHPStanDrupal\Tests\Rules\DeprecatedHookImplementationTest::testRule test for deprecated_field_widget_hooks_field_widget_form_alter
- \mglaman\PHPStanDrupal\Tests\Rules\GetDeprecatedServiceRuleTest::testRuleDrupal8
- \mglaman\PHPStanDrupal\Tests\Rules\GetDeprecatedServiceRuleTest::testRuleDrupal9
- \mglaman\PHPStanDrupal\Tests\Rules\RequestStackGetMainRequestRuleTest::testRule and the rule
- \mglaman\PHPStanDrupal\Tests\Rules\SymfonyCmfRouteObjectInterfaceConstantsRuleTest::testRule and the rule
- \mglaman\PHPStanDrupal\Tests\Rules\SymfonyCmfRoutingInClassMethodSignatureRuleTest::testRule and the rule

**Comment by alexb7217** [comment]
Personally, I have no need for Drupal 9 support. Generally, favoring accelerated + efficient development over legacy maintenance seems like a good idea.

**Comment by Boegie** [comment]
PHP 7.4/ 8.0 support has been dropped already, D9 is the only one still standing.
> > A new branch might be a nice clean cut-off point to drop D9 support?
> 
> We can say 2.x drops Drupal 9 support, as a follow up to his PR.
https://github.com/mglaman/phpstan-drupal/pull/805#issuecomment-2470920650
