### ISSUE TITLE
InstallerExistingConfigTestBase is going to be deprecated

### ISSUE THREAD

**Issue by nlighteneddesign** [mglaman/phpstan-drupal#780]
Issue: https://www.drupal.org/project/drupal/issues/3455820
Change Notice: https://www.drupal.org/node/3460001

Rule: https://github.com/mglaman/phpstan-drupal/blob/main/src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php#L74

**Comment by mglaman** [comment]
If the class is ragged as deprecated, this should just work and throw an error about extending the class.

**Comment by nlighteneddesign** [comment]
Yes, the deprecation will work, but you'll need to update the rule I linked for the new class, I think I can create an MR as the other issue gets closer.

**Comment by nlighteneddesign** [comment]
Here is the PR https://github.com/mglaman/phpstan-drupal/pull/781

**Comment by mglaman** [comment]
Oh I see, now
