### ISSUE TITLE
Uncaught error: Cannot unset string offsets

### ISSUE THREAD

**Issue by opdavies** [mglaman/phpstan-drupal#79]
I'm having issues getting this set up. When I try and run it, I get this error:

```
Note: Using configuration file /var/www/html/phpstan.neon.
PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /var/www/html/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php:152
Stack trace:
#0 /var/www/html/vendor/nette/di/src/DI/Compiler.php(229): PHPStan\DependencyInjection\DrupalExtension->loadConfiguration()
#1 /var/www/html/vendor/nette/di/src/DI/Compiler.php(204): Nette\DI\Compiler->processExtensions()
#2 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#3 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate('Container_bdd2b...', Array)
#4 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_bdd2b...', Array)
#5 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(242): Nette\DI\ContainerLoader->load(Array, Array)
#6 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(221): Nette\Configurator->loadContainer()
#7 /var/www/html/vendor/phpstan/phpstan/src/DependencyInjectio in /var/www/html/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php on line 152'
```

This is the command that I'm running, though I get the same output if I run it inside the container:

```
ddev exec -d /var/www/html vendor/bin/phpstan web/modules/custom
```

The site repo is at https://github.com/PHPSouthWales/php-south-wales-drupal, it's a Drupal 8.7.3 built based on https://github.com/drupal-composer/drupal-project. I'm running PHP 7.3, though I get the same with 7.2 or 7.1.

It's my first time trying to set this up, so I could definitely be doing something wrong!

**Comment by mglaman** [comment]
The line causing the error is https://github.com/mglaman/phpstan-drupal/blob/master/src/DependencyInjection/DrupalExtension.php#L152

```
unset($serviceDefinition['tags']);
```

Some how the service definition from a `services.yml` is not an array but is just a string?

**Comment by opdavies** [comment]
It seems to be related to the patches [on this issue](https://www.drupal.org/node/3021898). Now I've removed it, the error is gone.

**Comment by rasben** [comment]
Well, the patch that you mentioned has now been merged into core, meaning this is a problem again.
I've opened a new ticket: #477
