### ISSUE TITLE
Support phpstan/phpstan 2.0 by creating a new 2.x branch of this fine extension

### ISSUE THREAD

**Issue by Boegie** [mglaman/phpstan-drupal#806]
# Feature request

https://github.com/phpstan/phpstan/releases/tag/2.0.1 is out.

Since it's not possible to support both 1.x and 2.x in one branch, according to the maintainer, we need a new 2.x branch

**Comment by mglaman** [comment]
I wonder if `main` should become `2.x` and just open `1.x` off of `main`.

**Comment by Boegie** [comment]
That makes sense to me, since new development will mostly/only happen in `main`/`2.x` and maybe backported to `1.x` I assume?

**Comment by mglaman** [comment]
yeah, everything will have to be backported vs forwarded

**Comment by mglaman** [comment]
Opened https://github.com/mglaman/phpstan-drupal/tree/1.x, `main` will be tracking `2.x` of PHPStan
