### ISSUE TITLE
Ensure PHPStan 0.12 support

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#91]
😬 let's see if PHPStan 0.12 works with this extension.

**Comment by mglaman** [comment]
This won't work.

```
            if (!\is_a($class, \_HumbugBox3be60b26ad9d\Nette\DI\CompilerExtension::class, \true)) {
                throw new \_HumbugBox3be60b26ad9d\Nette\DI\InvalidConfigurationException("Extension should be Nette\\DI\\CompilerExtension, '{$class}' given.");
            }
```

This extension has to be completely rewritten to not use any components of `nette/di` to ensure Drupal is autoloaded.

**Comment by mglaman** [comment]
We can no longer use this:

```
extensions:
	drupal: PHPStan\DependencyInjection\DrupalExtension
```

This was a known weak point and I tried resolving in #71. 

I made this comment

```
	# @todo this must persist in a DI extension due unexpanded relative path.
	#autoload_files:
	#	- drupal-autoloader.php
```

Looks like fixing that is a hard requirement, now.

**Comment by mglaman** [comment]
> Dependencies from Nette\ and Symfony\ namespaces can no longer be used directly as they are prefixed in the PHAR with a random namespace. If you have a valid use-case, open an issue and we'll figure some interface to use it through.

🙃 right in the release notes https://github.com/phpstan/phpstan/releases/tag/0.12.0

**Comment by goba** [comment]
Well, you do have a valid use-case ;)
